# Hungarian translation of update-manager
# This file is distributed under the same license as the update-manager package.
# Copyright (C) 2005, Free Software Foundation, Inc.
# Gabor Kelemen <kelemeng@gnome.hu>, 2005.
#
msgid ""
msgstr ""
"Project-Id-Version: update-manager.HEAD\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2010-09-22 05:12+0000\n"
"PO-Revision-Date: 2010-09-23 13:42+0000\n"
"Last-Translator: Gabor Kelemen <kelemeng@gnome.hu>\n"
"Language-Team: Hungarian <gnome@gnome.hu>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=n != 1;\n"
"X-Launchpad-Export-Date: 2010-09-27 08:04+0000\n"
"X-Generator: Launchpad (build Unknown)\n"

#. TRANSLATORS: download size is 0
#: ../DistUpgrade/utils.py:346 ../UpdateManager/Core/utils.py:346
msgid "0 KB"
msgstr "0 KB"

#. TRANSLATORS: download size of very small updates
#: ../DistUpgrade/utils.py:349 ../UpdateManager/Core/utils.py:349
msgid "1 KB"
msgstr "1 KB"

#. TRANSLATORS: download size of small updates, e.g. "250 KB"
#: ../DistUpgrade/utils.py:352 ../UpdateManager/Core/utils.py:352
#, python-format
msgid "%.0f KB"
msgstr "%.0f KB"

#. TRANSLATORS: download size of updates, e.g. "2.3 MB"
#: ../DistUpgrade/utils.py:355 ../UpdateManager/Core/utils.py:355
#, python-format
msgid "%.1f MB"
msgstr "%.1f MB"

#. TRANSLATORS: %s is a country
#: ../DistUpgrade/distro.py:209 ../DistUpgrade/distro.py:424
#, python-format
msgid "Server for %s"
msgstr "Kiszolgáló a következőhöz: %s"

#. More than one server is used. Since we don't handle this case
#. in the user interface we set "custom servers" to true and
#. append a list of all used servers
#: ../DistUpgrade/distro.py:227 ../DistUpgrade/distro.py:233
#: ../DistUpgrade/distro.py:249
msgid "Main server"
msgstr "Fő kiszolgáló"

#: ../DistUpgrade/distro.py:253
msgid "Custom servers"
msgstr "Egyéni kiszolgálók"

#: ../DistUpgrade/DistUpgradeAptCdrom.py:131
msgid "Could not calculate sources.list entry"
msgstr "Nem határozható meg a sources.list bejegyzés"

#: ../DistUpgrade/DistUpgradeAptCdrom.py:234
msgid ""
"Unable to locate any package files, perhaps this is not a Ubuntu Disc or the "
"wrong architecture?"
msgstr ""
"Egyetlen csomagfájl sem található! Lehet, hogy nem Ubuntu lemezt, vagy más "
"architektúrához tartozót helyezett a meghajtóba."

#: ../DistUpgrade/DistUpgradeAptCdrom.py:277
msgid "Failed to add the CD"
msgstr "A CD hozzáadása meghiúsult"

#: ../DistUpgrade/DistUpgradeAptCdrom.py:278
#, python-format
msgid ""
"There was a error adding the CD, the upgrade will abort. Please report this "
"as a bug if this is a valid Ubuntu CD.\n"
"\n"
"The error message was:\n"
"'%s'"
msgstr ""
"Hiba történt a CD hozzáadása során, a frissítés félbeszakad. Jelentse ezt "
"hibaként, ha ez egy érvényes Ubuntu CD.\n"
"\n"
"A hibaüzenet:\n"
"„%s”"

#: ../DistUpgrade/DistUpgradeCache.py:130
msgid "Remove package in bad state"
msgid_plural "Remove packages in bad state"
msgstr[0] "Hibás állapotban levő csomag eltávolítása"
msgstr[1] "Hibás állapotban levő csomagok eltávolítása"

#: ../DistUpgrade/DistUpgradeCache.py:133
#, python-format
msgid ""
"The package '%s' is in an inconsistent state and needs to be reinstalled, "
"but no archive can be found for it. Do you want to remove this package now "
"to continue?"
msgid_plural ""
"The packages '%s' are in an inconsistent state and need to be reinstalled, "
"but no archives can be found for them. Do you want to remove these packages "
"now to continue?"
msgstr[0] ""
"A(z) „%s” nevű csomag hibás! Újratelepítése szükséges, azonban nem található "
"hozzá megfelelő archívum. El kívánja távolítani ezt a csomagot a "
"folytatáshoz?"
msgstr[1] ""
"A(z) „%s” nevű csomagok hibásak! Újratelepítésük szükséges, azonban nem "
"található hozzájuk megfelelő archívum. El kívánja távolítani ezeket a "
"csomagokat a folytatáshoz?"

#. FIXME: not ideal error message, but we just reuse a
#. existing one here to avoid a new string
#: ../DistUpgrade/DistUpgradeCache.py:231
msgid "The server may be overloaded"
msgstr "Lehet, hogy a kiszolgáló túlterhelt"

#: ../DistUpgrade/DistUpgradeCache.py:341
msgid "Broken packages"
msgstr "Törött csomagok"

#: ../DistUpgrade/DistUpgradeCache.py:342
msgid ""
"Your system contains broken packages that couldn't be fixed with this "
"software. Please fix them first using synaptic or apt-get before proceeding."
msgstr ""
"A rendszere törött csomagokat tartalmaz, amelyek ezzel az alkalmazással nem "
"javíthatóak. Kérem, először javítsa ki őket a synaptic vagy az apt-get "
"segítségével."

#. FIXME: change the text to something more useful
#: ../DistUpgrade/DistUpgradeCache.py:631
#, python-format
msgid ""
"An unresolvable problem occurred while calculating the upgrade:\n"
"%s\n"
"\n"
" This can be caused by:\n"
" * Upgrading to a pre-release version of Ubuntu\n"
" * Running the current pre-release version of Ubuntu\n"
" * Unofficial software packages not provided by Ubuntu\n"
"\n"
msgstr ""
"Megoldhatatlan probléma adódott a frissítés előkészítése közben:\n"
"%s\n"
"\n"
" Ezt az alábbiak okozhatták:\n"
" * frissítés egy kiadás előtti Ubuntu verzióra\n"
" * Ön jelenleg egy kiadás előtti Ubuntu verziót használ\n"
" * az Ubuntu által nem támogatott csomagok\n"
"\n"

#: ../DistUpgrade/DistUpgradeCache.py:641
msgid "This is most likely a transient problem, please try again later."
msgstr "Ez valószínűleg átmeneti probléma, próbálkozzon később."

#: ../DistUpgrade/DistUpgradeCache.py:644
msgid ""
"If none of this applies, then please report this bug against the 'update-"
"manager' package and include the files in /var/log/dist-upgrade/ in the bug "
"report."
msgstr ""
"Ha ezek közül egyik sem teljesül, jelentse ezt az „update-manager” csomaggal "
"kapcsolatos hibát és mellékelje a /var/log/dist-upgrade/ könyvtárban "
"található fájlokat a hibajelentéshez."

#: ../DistUpgrade/DistUpgradeCache.py:650
#: ../UpdateManager/UpdateManager.py:870
msgid "Could not calculate the upgrade"
msgstr "A frissítés előkészítése sikertelen"

#: ../DistUpgrade/DistUpgradeCache.py:700
msgid "Error authenticating some packages"
msgstr "Hiba történt néhány csomag hitelesítése közben"

#: ../DistUpgrade/DistUpgradeCache.py:701
msgid ""
"It was not possible to authenticate some packages. This may be a transient "
"network problem. You may want to try again later. See below for a list of "
"unauthenticated packages."
msgstr ""
"Néhány csomagot nem sikerült hitelesíteni. Lehetséges, hogy ezt átmeneti "
"hálózati probléma okozza, ezért érdemes később újra megpróbálni. Az alábbi "
"felsorolás a hitelesíthetetlen csomagokat tartalmazza."

#: ../DistUpgrade/DistUpgradeCache.py:721
#, python-format
msgid ""
"The package '%s' is marked for removal but it is in the removal blacklist."
msgstr ""
"A(z) „%s” nevű csomagot eltávolításra jelölte ki, de ez rajta van az "
"eltávolítási feketelistán."

#: ../DistUpgrade/DistUpgradeCache.py:725
#, python-format
msgid "The essential package '%s' is marked for removal."
msgstr "A létfontosságú „%s” csomagot eltávolításra jelölte ki."

#: ../DistUpgrade/DistUpgradeCache.py:734
#, python-format
msgid "Trying to install blacklisted version '%s'"
msgstr "Kísérlet a feketelistára tett „%s” verzió telepítésére"

#: ../DistUpgrade/DistUpgradeCache.py:836
#, python-format
msgid "Can not mark '%s' for upgrade"
msgstr "A(z) „%s” csomag nem jelölhető ki frissítésre."

#: ../DistUpgrade/DistUpgradeCache.py:850
#, python-format
msgid "Can't install '%s'"
msgstr "„%s” nem telepíthető"

#: ../DistUpgrade/DistUpgradeCache.py:851
msgid ""
"It was impossible to install a required package. Please report this as a "
"bug. "
msgstr "Egy szükséges csomag nem telepíthető. Kérem, jelentse ezt hibaként. "

#. FIXME: provide a list
#: ../DistUpgrade/DistUpgradeCache.py:860
msgid "Can't guess meta-package"
msgstr "A meta-csomag megállapítása sikertelen"

#: ../DistUpgrade/DistUpgradeCache.py:861
msgid ""
"Your system does not contain a ubuntu-desktop, kubuntu-desktop, xubuntu-"
"desktop or edubuntu-desktop package and it was not possible to detect which "
"version of Ubuntu you are running.\n"
" Please install one of the packages above first using synaptic or apt-get "
"before proceeding."
msgstr ""
"A rendszere nem tartalmazza az ubuntu-desktop, kubuntu-desktop, xubuntu-"
"desktop vagy edubuntu-desktop csomagok egyikét sem, és nem lehetett "
"megállapítani, hogy az Ubuntu mely változatát használja.\n"
" A folytatás előtt telepítse a fenti csomagok egyikét a synaptic vagy az apt-"
"get használatával."

#: ../DistUpgrade/DistUpgradeController.py:86
msgid "Reading cache"
msgstr "Gyorsítótár beolvasása"

#: ../DistUpgrade/DistUpgradeController.py:189
msgid "Unable to get exclusive lock"
msgstr "A kizárolagos zárolás nem lehetséges"

#: ../DistUpgrade/DistUpgradeController.py:190
msgid ""
"This usually means that another package management application (like apt-get "
"or aptitude) already running. Please close that application first."
msgstr ""
"Ez általában azt jelenti, hogy már fut egy másik csomagkezelő alkalmazás "
"(például apt-get vagy aptitude). Kérem először zárja be azt az alkalmazást."

#: ../DistUpgrade/DistUpgradeController.py:236
msgid "Upgrading over remote connection not supported"
msgstr "A frissítés nem támogatott távoli kapcsolaton keresztül"

#: ../DistUpgrade/DistUpgradeController.py:237
msgid ""
"You are running the upgrade over a remote ssh connection with a frontend "
"that does not support this. Please try a text mode upgrade with 'do-release-"
"upgrade'.\n"
"\n"
"The upgrade will abort now. Please try without ssh."
msgstr ""
"Távoli SSH-kapcsolaton keresztül futtatja a frissítést olyan felület "
"használatával, amely nem támogatja ezt. Próbálja meg szöveges módban "
"végrehajtani a frissítést a „do-release-upgrade” parancs segítségével.\n"
"\n"
"A frissítés most megszakad. Próbálja SSH nélkül."

#: ../DistUpgrade/DistUpgradeController.py:251
msgid "Continue running under SSH?"
msgstr "Folytatja a futtatást SSH alatt?"

#: ../DistUpgrade/DistUpgradeController.py:252
#, python-format
msgid ""
"This session appears to be running under ssh. It is not recommended to "
"perform a upgrade over ssh currently because in case of failure it is harder "
"to recover.\n"
"\n"
"If you continue, an additional ssh daemon will be started at port '%s'.\n"
"Do you want to continue?"
msgstr ""
"Úgy tűnik, ez a munkamenet SSH alatt fut. Jelenleg nem ajánlott, hogy SSH "
"kapcsolaton keresztül hajtsa végre a frissítést, ugyanis hiba esetén így "
"nehezebb a helyreállítás.\n"
"\n"
"Ha folytatja, egy újabb SSH-démon indul az alábbi porton: %s.\n"
"Szeretné folytatni?"

#: ../DistUpgrade/DistUpgradeController.py:267
msgid "Starting additional sshd"
msgstr "Új sshd indítása"

#: ../DistUpgrade/DistUpgradeController.py:268
#, python-format
msgid ""
"To make recovery in case of failure easier, an additional sshd will be "
"started on port '%s'. If anything goes wrong with the running ssh you can "
"still connect to the additional one.\n"
msgstr ""
"A hiba esetén történő helyreállítás megkönnyítése érdekében egy újabb sshd "
"indul a(z) %s porton. Ha bármiféle probléma lép fel az aktuális SSH futása "
"során, Ön továbbra is kapcsolódni tud majd a másik segítségével.\n"

#: ../DistUpgrade/DistUpgradeController.py:339
#: ../DistUpgrade/DistUpgradeController.py:384
msgid "Can not upgrade"
msgstr "Nem lehet frissíteni"

#: ../DistUpgrade/DistUpgradeController.py:340
#, python-format
msgid "An upgrade from '%s' to '%s' is not supported with this tool."
msgstr ""
"Ez az eszköz nem támogatja a frissítést „%s” rendszerről „%s” rendszerre."

#: ../DistUpgrade/DistUpgradeController.py:349
msgid "Sandbox setup failed"
msgstr "A tesztkörnyezet beállítása meghiúsult"

#: ../DistUpgrade/DistUpgradeController.py:350
msgid "It was not possible to create the sandbox environment."
msgstr "Nem sikerült létrehozni a tesztkörnyezetet."

#: ../DistUpgrade/DistUpgradeController.py:356
msgid "Sandbox mode"
msgstr "Teszt mód"

#: ../DistUpgrade/DistUpgradeController.py:357
#, python-format
msgid ""
"This upgrade is running in sandbox (test) mode. All changes are written to "
"'%s' and will be lost on the next reboot.\n"
"\n"
"*No* changes written to a systemdir from now until the next reboot are "
"permanent."
msgstr ""
"A frissítés teszt módban fut. Minden módosítás kiírásra kerül a(z) %s fájlba "
"és a következő újraindításkor elvész.\n"
"\n"
"Mostantól a következő újraindításig a rendszerkönyvtárakba írt változtatások "
"NEM véglegesek."

#: ../DistUpgrade/DistUpgradeController.py:385
msgid ""
"Your python install is corrupted. Please fix the '/usr/bin/python' symlink."
msgstr ""
"A Python telepítése sérült. Javítsa ki a „/usr/bin/python” szimbolikus "
"linket."

#: ../DistUpgrade/DistUpgradeController.py:411
msgid "Package 'debsig-verify' is installed"
msgstr "A „debsig-verify” csomag telepítve van"

#: ../DistUpgrade/DistUpgradeController.py:412
msgid ""
"The upgrade can not continue with that package installed.\n"
"Please remove it with synaptic or 'apt-get remove debsig-verify' first and "
"run the upgrade again."
msgstr ""
"A frissítés nem folytatódhat, ha ez a csomag telepítve van.\n"
"Távolítsa el a Synaptic vagy az „apt-get remove debsig-verify” parancs "
"kiadásával és futtassa újra a frissítést."

#: ../DistUpgrade/DistUpgradeController.py:422
msgid "Include latest updates from the Internet?"
msgstr "Használja az interneten elérhető legújabb frissítéseket?"

#: ../DistUpgrade/DistUpgradeController.py:423
msgid ""
"The upgrade system can use the internet to automatically download the latest "
"updates and install them during the upgrade.  If you have a network "
"connection this is highly recommended.\n"
"\n"
"The upgrade will take longer, but when it is complete, your system will be "
"fully up to date.  You can choose not to do this, but you should install the "
"latest updates soon after upgrading.\n"
"If you answer 'no' here, the network is not used at all."
msgstr ""
"A frissítőrendszer használhatja az internetet a legújabb frissítések "
"letöltéséhez és telepítheti azokat a frissítés közben. Ha rendelkezik "
"internetkapcsolattal, ez a beállítás erősen ajánlott.\n"
"\n"
"A frissítés hosszabb ideig is eltarthat, a folyamat végeztével a rendszere "
"teljesen naprakész lesz. Választhatja e funkció mellőzését is, azonban "
"ajánlott a legújabb frissítések telepítését elvégezni a rendszerfrissítés "
"után nem sokkal.\n"
"Ha a „Nem”-et választja, a telepítő nem fogja használni internetkapcsolatát."

#: ../DistUpgrade/DistUpgradeController.py:639
#, python-format
msgid "disabled on upgrade to %s"
msgstr "letiltva a(z) %s változatra frissítéskor"

#: ../DistUpgrade/DistUpgradeController.py:666
msgid "No valid mirror found"
msgstr "Nem található érvényes tükör"

#: ../DistUpgrade/DistUpgradeController.py:667
#, python-format
msgid ""
"While scanning your repository information no mirror entry for the upgrade "
"was found. This can happen if you run a internal mirror or if the mirror "
"information is out of date.\n"
"\n"
"Do you want to rewrite your 'sources.list' file anyway? If you choose 'Yes' "
"here it will update all '%s' to '%s' entries.\n"
"If you select 'No' the upgrade will cancel."
msgstr ""
"A tárolóinformációk elemzése során a program nem talált tükörbejegyzést a "
"frissítéshez. Ez akkor fordulhat elő, ha belső tükröt használ, vagy a "
"tükörinformációk elavultak.\n"
"\n"
"Mindenképpen újra kívánja írni a sources.list fájlt? Ha az „Igen” gombot "
"választja, akkor az összes „%s” bejegyzés „%s” bejegyzéssé lesz frissítve. A "
"„Nem” kiválasztása megszakítja a frissítést."

#. hm, still nothing useful ...
#: ../DistUpgrade/DistUpgradeController.py:687
msgid "Generate default sources?"
msgstr "Alapértelmezett források ismételt előállítása?"

#: ../DistUpgrade/DistUpgradeController.py:688
#, python-format
msgid ""
"After scanning your 'sources.list' no valid entry for '%s' was found.\n"
"\n"
"Should default entries for '%s' be added? If you select 'No', the upgrade "
"will cancel."
msgstr ""
"A „sources.list” átnézése után sem található érvényes bejegyzés a "
"következőről: %s.\n"
"\n"
"Hozzáadja az alap bejegyzéseket a következőhöz: „%s”? A „Nem” kiválasztása "
"megszakítja a frissítést."

#: ../DistUpgrade/DistUpgradeController.py:723
msgid "Repository information invalid"
msgstr "Érvénytelen tárolóinformációk"

#: ../DistUpgrade/DistUpgradeController.py:724
msgid ""
"Upgrading the repository information resulted in a invalid file. Please "
"report this as a bug."
msgstr ""
"A tárolóinformációk frissítése hibás fájlt eredményezett. Jelentse ezt "
"hibaként."

#: ../DistUpgrade/DistUpgradeController.py:730
msgid "Third party sources disabled"
msgstr "A külső források letiltva"

#: ../DistUpgrade/DistUpgradeController.py:731
msgid ""
"Some third party entries in your sources.list were disabled. You can re-"
"enable them after the upgrade with the 'software-properties' tool or your "
"package manager."
msgstr ""
"A sources.list néhány harmadik féltől származó forrása le lett tiltva. A "
"frissítés után újraengedélyezheti őket a Szoftverforrások eszközzel, vagy a "
"csomagkezelővel."

#: ../DistUpgrade/DistUpgradeController.py:771
msgid "Package in inconsistent state"
msgid_plural "Packages in inconsistent state"
msgstr[0] "Nem konzisztens állapotú csomag"
msgstr[1] "Nem konzisztens állapotú csomagok"

#: ../DistUpgrade/DistUpgradeController.py:774
#, python-format
msgid ""
"The package '%s' is in an inconsistent state and needs to be reinstalled, "
"but no archive can be found for it. Please reinstall the package manually or "
"remove it from the system."
msgid_plural ""
"The packages '%s' are in an inconsistent state and need to be reinstalled, "
"but no archive can be found for them. Please reinstall the packages manually "
"or remove them from the system."
msgstr[0] ""
"A(z) „%s” nevű csomag hibás! Újratelepítése szükséges, azonban nem található "
"hozzá megfelelő archívum. Telepítse újra a csomagot saját kezűleg, vagy "
"távolítsa el a rendszerről."
msgstr[1] ""
"A(z) „%s” nevű csomagok hibásak! Újratelepítésük szükséges, azonban nem "
"található hozzájuk megfelelő archívum. Telepítse újra a csomagot saját "
"kezűleg, vagy távolítsa el a rendszerről."

#: ../DistUpgrade/DistUpgradeController.py:822
msgid "Error during update"
msgstr "Hiba történt a frissítés közben"

#: ../DistUpgrade/DistUpgradeController.py:823
msgid ""
"A problem occurred during the update. This is usually some sort of network "
"problem, please check your network connection and retry."
msgstr ""
"Hiba lépett fel a frissítés közben. Ez többnyire hálózati problémára utal. "
"Kérem, ellenőrizze a hálózati kapcsolatot és próbálja újra."

#. print "on_button_install_clicked"
#: ../DistUpgrade/DistUpgradeController.py:832
#: ../UpdateManager/UpdateManager.py:628
msgid "Not enough free disk space"
msgstr "Nincs elég szabad hely a merevlemezen"

#: ../DistUpgrade/DistUpgradeController.py:833
#, python-format
msgid ""
"The upgrade has aborted. The upgrade needs a total of %s free space on disk "
"'%s'. Please free at least an additional %s of disk space on '%s'. Empty "
"your trash and remove temporary packages of former installations using 'sudo "
"apt-get clean'."
msgstr ""
"A frissítés megszakadt. A frissítéshez %s szabad hely szükséges a(z) „%s” "
"lemezen. Szabadítson fel további %s lemezterületet a(z) „%s” eszközön. "
"Ürítse a Kukát és törölje a korábbi telepítések átmeneti fájljait a „sudo "
"apt-get clean” parancs kiadásával."

#. calc the dist-upgrade and see if the removals are ok/expected
#. do the dist-upgrade
#: ../DistUpgrade/DistUpgradeController.py:861
#: ../DistUpgrade/DistUpgradeController.py:1577
msgid "Calculating the changes"
msgstr "Módosítások előkészítése"

#. ask the user
#: ../DistUpgrade/DistUpgradeController.py:893
msgid "Do you want to start the upgrade?"
msgstr "Biztosan el szeretné kezdeni a frissítést?"

#: ../DistUpgrade/DistUpgradeController.py:959
msgid "Upgrade canceled"
msgstr "Frissítés megszakítva"

#: ../DistUpgrade/DistUpgradeController.py:960
msgid ""
"The upgrade cancels now and the original system state is restored. You can "
"resume the upgrade at a later time."
msgstr ""
"A frissítés megszakadt és az eredeti rendszerállapot lett visszaállítva. "
"Később folytatható a frissítés."

#: ../DistUpgrade/DistUpgradeController.py:965
#: ../DistUpgrade/DistUpgradeController.py:1064
msgid "Could not download the upgrades"
msgstr "A frissítések nem tölthetők le"

#: ../DistUpgrade/DistUpgradeController.py:966
msgid ""
"The upgrade has aborted. Please check your Internet connection or "
"installation media and try again. All files downloaded so far are kept."
msgstr ""
"A frissítés megszakadt. Ellenőrizze az internetkapcsolatát vagy a telepítési "
"adathordozót, és próbálja újra. Minden eddig letöltött fájl megmaradt."

#. FIXME: strings are not good, but we are in string freeze
#. currently
#: ../DistUpgrade/DistUpgradeController.py:1016
#: ../DistUpgrade/DistUpgradeController.py:1052
#: ../DistUpgrade/DistUpgradeController.py:1157
msgid "Error during commit"
msgstr "Hiba a módosítások rögzítése közben"

#. generate a new cache
#: ../DistUpgrade/DistUpgradeController.py:1018
#: ../DistUpgrade/DistUpgradeController.py:1054
#: ../DistUpgrade/DistUpgradeController.py:1196
msgid "Restoring original system state"
msgstr "A rendszer eredeti állapotának helyreállítása"

#: ../DistUpgrade/DistUpgradeController.py:1019
#: ../DistUpgrade/DistUpgradeController.py:1033
#: ../DistUpgrade/DistUpgradeController.py:1055
msgid "Could not install the upgrades"
msgstr "A frissítések nem telepíthetők"

#. invoke the frontend now and show a error message
#: ../DistUpgrade/DistUpgradeController.py:1024
msgid ""
"The upgrade has aborted. Your system could be in an unusable state. A "
"recovery will run now (dpkg --configure -a)."
msgstr ""
"A frissítés megszakadt. A rendszer használhatatlan állapotban lehet. A "
"helyreállítás azonnal indul (dpkg --configure -a)."

#: ../DistUpgrade/DistUpgradeController.py:1029
#, python-format
msgid ""
"\n"
"\n"
"Please report this bug against the 'update-manager' package and include the "
"files in /var/log/dist-upgrade/ in the bug report.\n"
"%s"
msgstr ""
"\n"
"\n"
"A frissítés most megszakadt. Jelentse ezt a hibát az „update-manager” "
"csomaghoz és vegye be a /var/log/dist-upgrade/ könyvtárban található "
"fájlokat a hibajelentésbe.\n"
"%s"

#: ../DistUpgrade/DistUpgradeController.py:1065
msgid ""
"The upgrade has aborted. Please check your Internet connection or "
"installation media and try again. "
msgstr ""
"A frissítés megszakadt. Ellenőrizze az internetkapcsolatát vagy a telepítési "
"adathordozót, és próbálja újra. "

#: ../DistUpgrade/DistUpgradeController.py:1145
msgid "Remove obsolete packages?"
msgstr "Eltávolítja az elavult csomagokat?"

#: ../DistUpgrade/DistUpgradeController.py:1146
#: ../DistUpgrade/DistUpgrade.ui.h:22
msgid "_Keep"
msgstr "_Megtartás"

#: ../DistUpgrade/DistUpgradeController.py:1146
msgid "_Remove"
msgstr "_Eltávolítás"

#: ../DistUpgrade/DistUpgradeController.py:1158
msgid ""
"A problem occurred during the clean-up. Please see the below message for "
"more information. "
msgstr ""
"A frissítés befejező fázisa közben hiba lépett fel. Az alábbi üzenet további "
"információkat tartalmaz a hibára vonatkozóan. "

#. FIXME: instead of error out, fetch and install it
#. here
#: ../DistUpgrade/DistUpgradeController.py:1234
msgid "Required depends is not installed"
msgstr "A szükséges függőségek nincsenek telepítve"

#: ../DistUpgrade/DistUpgradeController.py:1235
#, python-format
msgid "The required dependency '%s' is not installed. "
msgstr "A következő függőség nincs telepítve: %s. "

#. sanity check (check for ubuntu-desktop, brokenCache etc)
#. then open the cache (again)
#: ../DistUpgrade/DistUpgradeController.py:1480
#: ../DistUpgrade/DistUpgradeController.py:1547
msgid "Checking package manager"
msgstr "Csomagkezelő ellenőrzése"

#: ../DistUpgrade/DistUpgradeController.py:1485
msgid "Preparing the upgrade failed"
msgstr "A frissítés előkészítése meghiúsult"

#: ../DistUpgrade/DistUpgradeController.py:1486
msgid ""
"Preparing the system for the upgrade failed. Please report this as a bug "
"against the 'update-manager' package and include the files in /var/log/dist-"
"upgrade/ in the bug report."
msgstr ""
"A rendszer frissítésre való előkészítése meghiúsult. Jelentse ezt a hibát az "
"„update-manager” csomaghoz és vegye be a /var/log/dist-upgrade/ könyvtárban "
"található fájlokat a hibajelentésbe."

#: ../DistUpgrade/DistUpgradeController.py:1502
msgid "Getting upgrade prerequisites failed"
msgstr "A frissítés előfeltételeinek lekérése meghiúsult"

#: ../DistUpgrade/DistUpgradeController.py:1503
msgid ""
"The system was unable to get the prerequisites for the upgrade. The upgrade "
"will abort now and restore the original system state.\n"
"\n"
"Please report this as a bug against the 'update-manager' package and include "
"the files in /var/log/dist-upgrade/ in the bug report."
msgstr ""
"A rendszer nem volt képes lekérni a frissítés előfeltételeit. A frissítés "
"most megszakad és helyreáll a rendszer eredeti állapota.\n"
"\n"
"Jelentse ezt a hibát az „update-manager” csomaghoz és vegye be a "
"/var/log/dist-upgrade/ könyvtárban található fájlokat a hibajelentésbe."

#: ../DistUpgrade/DistUpgradeController.py:1533
msgid "Updating repository information"
msgstr "Tárolóinformációk frissítése"

#: ../DistUpgrade/DistUpgradeController.py:1565
msgid "Invalid package information"
msgstr "Érvénytelen csomaginformációk"

#: ../DistUpgrade/DistUpgradeController.py:1566
#, python-format
msgid ""
"After your package information was updated the essential package '%s' can "
"not be found anymore.\n"
"This indicates a serious error, please report this bug against the 'update-"
"manager' package and include the files in /var/log/dist-upgrade/ in the bug "
"report."
msgstr ""
"A csomaginformációk frissítése után a(z) „%s” alapvető csomag már nem "
"található. Ez egy komoly problémát jelez, jelentse ezt a hibát az „update-"
"manager” csomaghoz és vegye be a /var/log/dist-upgrade/ könyvtárban "
"található fájlokat a hibajelentésbe."

#: ../DistUpgrade/DistUpgradeController.py:1583
#: ../DistUpgrade/DistUpgradeController.py:1631
msgid "Fetching"
msgstr "Letöltés"

#: ../DistUpgrade/DistUpgradeController.py:1589
#: ../DistUpgrade/DistUpgradeController.py:1635
msgid "Upgrading"
msgstr "Frissítés"

#. don't abort here, because it would restore the sources.list
#: ../DistUpgrade/DistUpgradeController.py:1594
#: ../DistUpgrade/DistUpgradeController.py:1637
#: ../DistUpgrade/DistUpgradeController.py:1644
#: ../DistUpgrade/DistUpgradeController.py:1655
msgid "Upgrade complete"
msgstr "A frissítés befejeződött"

#: ../DistUpgrade/DistUpgradeController.py:1595
#: ../DistUpgrade/DistUpgradeController.py:1638
#: ../DistUpgrade/DistUpgradeController.py:1645
msgid ""
"The upgrade is completed but there were errors during the upgrade process."
msgstr ""
"A frissítés befejeződött, de hibák történtek a frissítési folyamat során."

#: ../DistUpgrade/DistUpgradeController.py:1602
msgid "Searching for obsolete software"
msgstr "Elavult szoftverek keresése"

#: ../DistUpgrade/DistUpgradeController.py:1607
msgid "System upgrade is complete."
msgstr "A rendszer frissítése befejeződött."

#: ../DistUpgrade/DistUpgradeController.py:1656
msgid "The partial upgrade was completed."
msgstr "Az intelligens frissítés sikeresen befejeződött."

#: ../DistUpgrade/DistUpgradeQuirks.py:168
msgid "evms in use"
msgstr "Az evms használatban van"

#: ../DistUpgrade/DistUpgradeQuirks.py:169
msgid ""
"Your system uses the 'evms' volume manager in /proc/mounts. The 'evms' "
"software is no longer supported, please switch it off and run the upgrade "
"again when this is done."
msgstr ""
"A rendszer az „evms” kötetkezelőt használja a /proc/mounts alatt. Az „evms” "
"szoftver már nem támogatott, kapcsolja ki és futtassa újra a frissítést."

#: ../DistUpgrade/DistUpgradeQuirks.py:434
#: ../DistUpgrade/DistUpgradeQuirks.py:462
#: ../DistUpgrade/DistUpgradeQuirks.py:489
msgid ""
"Upgrading may reduce desktop effects, and performance in games and other "
"graphically intensive programs."
msgstr ""
"A frissítés visszafoghatja a vizuális effektusokat, a játékok és a sok "
"grafikai számítást igénylő alkalmazások teljesítményét."

#: ../DistUpgrade/DistUpgradeQuirks.py:438
#: ../DistUpgrade/DistUpgradeQuirks.py:466
msgid ""
"This computer is currently using the NVIDIA 'nvidia' graphics driver. No "
"version of this driver is available that works with your video card in "
"Ubuntu 10.04 LTS.\n"
"\n"
"Do you want to continue?"
msgstr ""
"Ez a számítógép jelenleg az NVIDIA „nvidia” grafikus meghajtóját használja. "
"Ennek a meghajtónak nem érhető el a videokártyáját az Ubuntu 10.04 LTS alatt "
"kezelni képes verziója.\n"
"\n"
"Biztosan folytatja?"

#: ../DistUpgrade/DistUpgradeQuirks.py:493
msgid ""
"This computer is currently using the AMD 'fglrx' graphics driver. No version "
"of this driver is available that works with your hardware in Ubuntu 10.04 "
"LTS.\n"
"\n"
"Do you want to continue?"
msgstr ""
"Ez a számítógép jelenleg az AMD „fglrx” grafikus meghajtóját használja. "
"Ennek a meghajtónak nem érhető el a hardverét az Ubuntu 10.04 LTS alatt "
"kezelni képes verziója.\n"
"\n"
"Biztosan folytatja?"

#: ../DistUpgrade/DistUpgradeQuirks.py:520
msgid "No ARMv6 CPU"
msgstr "Nem ARMv6 processzor"

#: ../DistUpgrade/DistUpgradeQuirks.py:521
msgid ""
"Your system uses an ARM CPU that is older than the ARMv6 architecture. All "
"packages in karmic were built with optimizations requiring ARMv6 as the "
"minimal architecture. It is not possible to upgrade your system to a new "
"Ubuntu release with this hardware."
msgstr ""
"A számítógépe ARMv6-nál régebbi ARM architektúrájú processzorral "
"rendelkezik. A Karmicban minden csomag legalább ARMv6-ot igénylő "
"optimalizációkkal készült. Ezen a hardveren nem frissíthető a rendszer új "
"Ubuntu kiadásra."

#: ../DistUpgrade/DistUpgradeQuirks.py:541
msgid "No init available"
msgstr "Nem érhető el init"

#: ../DistUpgrade/DistUpgradeQuirks.py:542
msgid ""
"Your system appears to be a virtualised environment without an init daemon, "
"e.g. Linux-VServer. Ubuntu 10.04 LTS cannot function within this type of "
"environment, requiring an update to your virtual machine configuration "
"first.\n"
"\n"
"Are you sure you want to continue?"
msgstr ""
"Úgy tűnik, hogy a rendszere egy virtualizált környezet init démon nélkül, "
"például Linux-VServer. Az Ubuntu 10.04 nem képes működni ebben a "
"környezetben, előbb frissítenie kell a virtuális gép beállításait.\n"
"\n"
"Biztosan folytatja?"

#: ../DistUpgrade/DistUpgradeMain.py:47
msgid "Sandbox upgrade using aufs"
msgstr "Tesztfrissítés aufs használatával"

#: ../DistUpgrade/DistUpgradeMain.py:49
msgid "Use the given path to search for a cdrom with upgradable packages"
msgstr ""
"A megadott útvonalat használja frissíthető csomagokat tartalmazó CD lemez "
"kereséséhez"

#: ../DistUpgrade/DistUpgradeMain.py:55
msgid ""
"Use frontend. Currently available: \n"
"DistUpgradeViewText, DistUpgradeViewGtk, DistUpgradeViewKDE"
msgstr ""
"Használja a kezelőfelületet. Jelenleg elérhető: \n"
"DistUpgradeViewText, DistUpgradeViewGtk, DistUpgradeViewKDE"

#: ../DistUpgrade/DistUpgradeMain.py:58
msgid "*DEPRECATED* this option will be ignore"
msgstr "*ÉRVÉNYTELENÍTVE* ez az opció meg fog szűnni"

#: ../DistUpgrade/DistUpgradeMain.py:61
msgid "Perform a partial upgrade only (no sources.list rewriting)"
msgstr ""
"Csak intelligens frissítés végrehajtása (nem írja újra a sources.list fájlt)"

#: ../DistUpgrade/DistUpgradeMain.py:63
msgid "Set datadir"
msgstr "Adatkönyvtár beállítása"

#. print "mediaChange %s %s" % (medium, drive)
#: ../DistUpgrade/DistUpgradeViewGtk.py:113
#: ../DistUpgrade/DistUpgradeViewKDE.py:190
#: ../UpdateManager/DistUpgradeFetcherKDE.py:148
#, python-format
msgid "Please insert '%s' into the drive '%s'"
msgstr "Helyezze be a(z) „%s” adathordozót a(z) „%s” meghajtóba."

#: ../DistUpgrade/DistUpgradeViewGtk.py:134
#: ../DistUpgrade/DistUpgradeViewKDE.py:204
msgid "Fetching is complete"
msgstr "A letöltés befejeződött"

#: ../DistUpgrade/DistUpgradeViewGtk.py:145
#: ../DistUpgrade/DistUpgradeViewKDE.py:217
#, python-format
msgid "Fetching file %li of %li at %sB/s"
msgstr "Fájl letöltése: %li / %li, (%sB/s)"

#: ../DistUpgrade/DistUpgradeViewGtk.py:148
#: ../DistUpgrade/DistUpgradeViewGtk.py:288
#: ../DistUpgrade/DistUpgradeViewKDE.py:218
#: ../DistUpgrade/DistUpgradeViewKDE.py:358
#, python-format
msgid "About %s remaining"
msgstr "Kb. %s van hátra"

#: ../DistUpgrade/DistUpgradeViewGtk.py:151
#: ../DistUpgrade/DistUpgradeViewKDE.py:220
#, python-format
msgid "Fetching file %li of %li"
msgstr "%li. fájl letöltése (összesen: %li)"

#. FIXME: add support for the timeout
#. of the terminal (to display something useful then)
#. -> longer term, move this code into python-apt
#: ../DistUpgrade/DistUpgradeViewGtk.py:183
#: ../DistUpgrade/DistUpgradeViewKDE.py:254
msgid "Applying changes"
msgstr "Módosítások alkalmazása"

#. we do not report followup errors from earlier failures
#: ../DistUpgrade/DistUpgradeViewGtk.py:208
#: ../DistUpgrade/DistUpgradeViewKDE.py:267
msgid "dependency problems - leaving unconfigured"
msgstr "függőségi hibák - a csomag beállítatlan maradt"

#: ../DistUpgrade/DistUpgradeViewGtk.py:213
#: ../DistUpgrade/DistUpgradeViewKDE.py:269
#, python-format
msgid "Could not install '%s'"
msgstr "„%s” nem telepíthető"

#: ../DistUpgrade/DistUpgradeViewGtk.py:214
#: ../DistUpgrade/DistUpgradeViewKDE.py:270
#, python-format
msgid ""
"The upgrade will continue but the '%s' package may not be in a working "
"state. Please consider submitting a bug report about it."
msgstr ""
"A frissítés folytatódik, de a(z) „%s” csomag működésképtelen állapotban "
"lehet. Ezzel kapcsolatban küldjön be hibajelentést."

#. self.expander.set_expanded(True)
#: ../DistUpgrade/DistUpgradeViewGtk.py:231
#: ../DistUpgrade/DistUpgradeViewKDE.py:291
#, python-format
msgid ""
"Replace the customized configuration file\n"
"'%s'?"
msgstr ""
"Lecseréli a személyre szabott\n"
"„%s”\n"
"konfigurációs fájlt?"

#: ../DistUpgrade/DistUpgradeViewGtk.py:232
#: ../DistUpgrade/DistUpgradeViewKDE.py:292
msgid ""
"You will lose any changes you have made to this configuration file if you "
"choose to replace it with a newer version."
msgstr ""
"A beállítófájl összes módosítása elvész, ha lecseréli az újabb verzióra."

#: ../DistUpgrade/DistUpgradeViewGtk.py:246
#: ../DistUpgrade/DistUpgradeViewKDE.py:310
msgid "The 'diff' command was not found"
msgstr "A „diff” parancs nem található"

#: ../DistUpgrade/DistUpgradeViewGtk.py:454
#: ../DistUpgrade/DistUpgradeViewText.py:88
msgid "A fatal error occurred"
msgstr "Végzetes hiba történt"

#: ../DistUpgrade/DistUpgradeViewGtk.py:455
msgid ""
"Please report this as a bug (if you haven't already) and include the files "
"/var/log/dist-upgrade/main.log and /var/log/dist-upgrade/apt.log in your "
"report. The upgrade has aborted.\n"
"Your original sources.list was saved in /etc/apt/sources.list.distUpgrade."
msgstr ""
"Jelentse ezt a hibát (ha eddig még nem tette volna) és csatolja a "
"/var/log/dist-upgrade/main.log és /var/log/dist-upgrade/apt.log nevű "
"fájlokat. A frissítés megszakadt. Az eredeti sources.list "
"/etc/apt/sources.list.distUpgrade néven került mentésre."

#: ../DistUpgrade/DistUpgradeViewGtk.py:472
msgid "Ctrl-c pressed"
msgstr "Ctrl+C billentyűkombináció lenyomva"

#: ../DistUpgrade/DistUpgradeViewGtk.py:473
msgid ""
"This will abort the operation and may leave the system in a broken state. "
"Are you sure you want to do that?"
msgstr ""
"Ez megszakítja a műveletet, és törött állapotban hagyhatja a rendszert. "
"Biztos, hogy ezt akarja tenni?"

#. append warning
#: ../DistUpgrade/DistUpgradeViewGtk.py:621
msgid "To prevent data loss close all open applications and documents."
msgstr ""
"Az esetleges adatvesztés elkerülése érdekében zárjon be minden nyitott "
"alkalmazást és dokumentumot."

#: ../DistUpgrade/DistUpgradeViewGtk.py:635
#, python-format
msgid "No longer supported by Canonical (%s)"
msgstr "A Canonical már nem támogatja (%s)"

#: ../DistUpgrade/DistUpgradeViewGtk.py:636
#, python-format
msgid "<b>Downgrade (%s)</b>"
msgstr "<b>Visszafejlesztendő (%s)</b>"

#: ../DistUpgrade/DistUpgradeViewGtk.py:637
#, python-format
msgid "Remove (%s)"
msgstr "Eltávolítás (%s)"

#: ../DistUpgrade/DistUpgradeViewGtk.py:638
#, python-format
msgid "No longer needed (%s)"
msgstr "Már nem szükséges (%s)"

#: ../DistUpgrade/DistUpgradeViewGtk.py:639
#, python-format
msgid "Install (%s)"
msgstr "Telepítés (%s)"

#: ../DistUpgrade/DistUpgradeViewGtk.py:640
#, python-format
msgid "Upgrade (%s)"
msgstr "Frissítés (%s)"

#. change = QMessageBox.question(None, _("Media Change"), msg, QMessageBox.Ok, QMessageBox.Cancel)
#: ../DistUpgrade/DistUpgradeViewKDE.py:191
#: ../UpdateManager/DistUpgradeFetcherKDE.py:150
msgid "Media Change"
msgstr "Adathordozó-csere"

#: ../DistUpgrade/DistUpgradeViewKDE.py:322
msgid "Show Difference >>>"
msgstr "Különbség megjelenítése >>>"

#: ../DistUpgrade/DistUpgradeViewKDE.py:325
msgid "<<< Hide Difference"
msgstr "<<< Különbség elrejtése"

#: ../DistUpgrade/DistUpgradeViewKDE.py:539
msgid "Error"
msgstr "Hiba"

#: ../DistUpgrade/DistUpgradeViewKDE.py:551
msgid "&Cancel"
msgstr "&Mégse"

#: ../DistUpgrade/DistUpgradeViewKDE.py:553
#: ../DistUpgrade/DistUpgradeViewKDE.py:795
msgid "&Close"
msgstr "&Bezárás"

#: ../DistUpgrade/DistUpgradeViewKDE.py:599
msgid "Show Terminal >>>"
msgstr "Terminál megjelenítése >>>"

#: ../DistUpgrade/DistUpgradeViewKDE.py:602
msgid "<<< Hide Terminal"
msgstr "<<< Terminál elrejtése"

#: ../DistUpgrade/DistUpgradeViewKDE.py:682
msgid "Information"
msgstr "Információ"

#: ../DistUpgrade/DistUpgradeViewKDE.py:733
#: ../DistUpgrade/DistUpgradeViewKDE.py:778
#: ../DistUpgrade/DistUpgradeViewKDE.py:781 ../DistUpgrade/DistUpgrade.ui.h:11
msgid "Details"
msgstr "Részletek"

#: ../DistUpgrade/DistUpgradeViewKDE.py:759
#, python-format
msgid "No longer supported %s"
msgstr "Már nem támogatott: %s"

#: ../DistUpgrade/DistUpgradeViewKDE.py:761
#, python-format
msgid "Remove %s"
msgstr "%s eltávolítása"

#: ../DistUpgrade/DistUpgradeViewKDE.py:763
#: ../DistUpgrade/DistUpgradeViewText.py:175
#, python-format
msgid "Remove (was auto installed) %s"
msgstr "%s eltávolítása (automatikusan telepített)"

#: ../DistUpgrade/DistUpgradeViewKDE.py:765
#, python-format
msgid "Install %s"
msgstr "%s telepítése"

#: ../DistUpgrade/DistUpgradeViewKDE.py:767
#, python-format
msgid "Upgrade %s"
msgstr "%s frissítése"

#: ../DistUpgrade/DistUpgradeViewKDE.py:791
#: ../DistUpgrade/DistUpgradeViewText.py:223
msgid "Restart required"
msgstr "Újraindítás szükséges"

#: ../DistUpgrade/DistUpgradeViewKDE.py:791
msgid "<b><big>Restart the system to complete the upgrade</big></b>"
msgstr "<b><big>Indítsa újra a rendszert a frissítés befejezéséhez</big></b>"

#: ../DistUpgrade/DistUpgradeViewKDE.py:794 ../DistUpgrade/DistUpgrade.ui.h:25
#: ../data/glade/UpdateManager.ui.h:31
msgid "_Restart Now"
msgstr "Újrain_dítás most"

#. FIXME make this user friendly
#: ../DistUpgrade/DistUpgradeViewKDE.py:812
msgid ""
"<b><big>Cancel the running upgrade?</big></b>\n"
"\n"
"The system could be in an unusable state if you cancel the upgrade. You are "
"strongly advised to resume the upgrade."
msgstr ""
"<b><big>Megszakítja a frissítést?</big></b>\n"
"\n"
"Lehet, hogy a rendszer használhatatlanná válik, ha most megszakítja a "
"frissítést. Erősen ajánlott a frissítés folytatása!"

#: ../DistUpgrade/DistUpgradeViewKDE.py:816
msgid "Cancel Upgrade?"
msgstr "Megszakítja a frissítést?"

#: ../DistUpgrade/DistUpgradeView.py:60
#, python-format
msgid "%li day"
msgid_plural "%li days"
msgstr[0] "%li nap"
msgstr[1] "%li nap"

#: ../DistUpgrade/DistUpgradeView.py:62
#, python-format
msgid "%li hour"
msgid_plural "%li hours"
msgstr[0] "%li óra"
msgstr[1] "%li óra"

#: ../DistUpgrade/DistUpgradeView.py:64
#, python-format
msgid "%li minute"
msgid_plural "%li minutes"
msgstr[0] "%li perc"
msgstr[1] "%li perc"

#: ../DistUpgrade/DistUpgradeView.py:65
#, python-format
msgid "%li second"
msgid_plural "%li seconds"
msgstr[0] "%li másodperc"
msgstr[1] "%li másodperc"

#. TRANSLATORS: you can alter the ordering of the remaining time
#. information here if you shuffle %(str_days)s %(str_hours)s %(str_minutes)s
#. around. Make sure to keep all '$(str_*)s' in the translated string
#. and do NOT change anything appart from the ordering.
#. 
#. %(str_hours)s will be either "1 hour" or "2 hours" depending on the
#. plural form
#. 
#. Note: most western languages will not need to change this
#: ../DistUpgrade/DistUpgradeView.py:81
#, python-format
msgid "%(str_days)s %(str_hours)s"
msgstr "%(str_days)s %(str_hours)s"

#. TRANSLATORS: you can alter the ordering of the remaining time
#. information here if you shuffle %(str_hours)s %(str_minutes)s
#. around. Make sure to keep all '$(str_*)s' in the translated string
#. and do NOT change anything appart from the ordering.
#. 
#. %(str_hours)s will be either "1 hour" or "2 hours" depending on the
#. plural form
#. 
#. Note: most western languages will not need to change this
#: ../DistUpgrade/DistUpgradeView.py:99
#, python-format
msgid "%(str_hours)s %(str_minutes)s"
msgstr "%(str_hours)s %(str_minutes)s"

#. 56 kbit
#. 1Mbit = 1024 kbit
#: ../DistUpgrade/DistUpgradeView.py:147
#, python-format
msgid ""
"This download will take about %s with a 1Mbit DSL connection and about %s "
"with a 56k modem."
msgstr ""
"A letöltés körülbelül %s alatt fejeződik be 1 megabites DSL kapcsolaton, és "
"%s alatt 56k-s modem használatával."

#. if we have a estimated speed, use it
#: ../DistUpgrade/DistUpgradeView.py:151
#, python-format
msgid "This download will take about %s with your connection. "
msgstr "A letöltés körülbelül %s alatt fejeződik be ezen a kapcsolaton. "

#: ../DistUpgrade/DistUpgradeView.py:253 ../DistUpgrade/DistUpgrade.ui.h:16
msgid "Preparing to upgrade"
msgstr "Felkészülés a frissítésre"

#: ../DistUpgrade/DistUpgradeView.py:254
msgid "Getting new software channels"
msgstr "Új szoftvercsatornák lekérése"

#: ../DistUpgrade/DistUpgradeView.py:255 ../DistUpgrade/DistUpgrade.ui.h:14
msgid "Getting new packages"
msgstr "Új csomagok letöltése"

#: ../DistUpgrade/DistUpgradeView.py:256 ../DistUpgrade/DistUpgrade.ui.h:15
msgid "Installing the upgrades"
msgstr "A frissítések telepítése"

#: ../DistUpgrade/DistUpgradeView.py:257 ../DistUpgrade/DistUpgrade.ui.h:10
msgid "Cleaning up"
msgstr "Frissítés befejezése"

#: ../DistUpgrade/DistUpgradeView.py:341
#, python-format
msgid ""
"%(amount)d installed package is no longer supported by Canonical. You can "
"still get support from the community."
msgid_plural ""
"%(amount)d installed packages are no longer supported by Canonical. You can "
"still get support from the community."
msgstr[0] ""
"%(amount)d szoftvercsomagot a Canonical már nem támogat. A közösségtől "
"továbbra is kaphat támogatást."
msgstr[1] ""
"%(amount)d szoftvercsomagot a Canonical már nem támogat. A közösségtől "
"továbbra is kaphat támogatást."

#. FIXME: make those two separate lines to make it clear
#. that the "%" applies to the result of ngettext
#: ../DistUpgrade/DistUpgradeView.py:350
#, python-format
msgid "%d package is going to be removed."
msgid_plural "%d packages are going to be removed."
msgstr[0] "%d csomag el lesz távolítva."
msgstr[1] "%d csomag el lesz távolítva."

#: ../DistUpgrade/DistUpgradeView.py:355
#, python-format
msgid "%d new package is going to be installed."
msgid_plural "%d new packages are going to be installed."
msgstr[0] "%d új csomag lesz telepítve."
msgstr[1] "%d új csomag lesz telepítve."

#: ../DistUpgrade/DistUpgradeView.py:361
#, python-format
msgid "%d package is going to be upgraded."
msgid_plural "%d packages are going to be upgraded."
msgstr[0] "%d csomag lesz frissítve."
msgstr[1] "%d csomag lesz frissítve."

#: ../DistUpgrade/DistUpgradeView.py:366
#, python-format
msgid ""
"\n"
"\n"
"You have to download a total of %s. "
msgstr ""
"\n"
"\n"
"Összes letöltendő adatmennyiség: %s. "

#: ../DistUpgrade/DistUpgradeView.py:370
msgid ""
"Fetching and installing the upgrade can take several hours. Once the "
"download has finished, the process cannot be cancelled."
msgstr ""
"A frissítés letöltése és telepítése több órát is igénybe vehet és a letöltés "
"befejeződése után már nem szakítható meg."

#. FIXME: this should go into DistUpgradeController
#: ../DistUpgrade/DistUpgradeView.py:376 ../UpdateManager/UpdateManager.py:557
msgid "Your system is up-to-date"
msgstr "A rendszere naprakész"

#: ../DistUpgrade/DistUpgradeView.py:377
msgid ""
"There are no upgrades available for your system. The upgrade will now be "
"canceled."
msgstr ""
"Nem állnak rendelkezésre frissítések a rendszeréhez. A frissítés most "
"megszakad."

#: ../DistUpgrade/DistUpgradeView.py:390
msgid "Reboot required"
msgstr "Újraindítás szükséges"

#: ../DistUpgrade/DistUpgradeView.py:391
msgid ""
"The upgrade is finished and a reboot is required. Do you want to do this now?"
msgstr ""
"A frissítés elkészült, de a befejezéshez újra kell indítani a rendszert. "
"Újraindítja most?"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:135
#: ../DistUpgrade/DistUpgradeFetcherCore.py:136
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:135
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:136
msgid "Could not run the upgrade tool"
msgstr "Nem sikerült futtatni a frissítőeszközt"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:136
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:136
msgid ""
"This is most likely a bug in the upgrade tool. Please report it as a bug"
msgstr ""
"Feltehetőleg ez egy hiba a frissítőeszközben. Kérem, jelentse ezt hibaként."

#: ../DistUpgrade/DistUpgradeFetcherCore.py:205
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:205
msgid "Upgrade tool signature"
msgstr "Frissítőeszköz aláírása"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:208
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:208
msgid "Upgrade tool"
msgstr "Frissítőeszköz"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:237
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:237
msgid "Failed to fetch"
msgstr "A letöltés meghiúsult"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:238
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:238
msgid "Fetching the upgrade failed. There may be a network problem. "
msgstr ""
"A frissítés letöltése meghiúsult. Lehetséges, hogy hálózati probléma áll "
"fenn. "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:242
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:242
msgid "Failed to extract"
msgstr "A kibontás meghiúsult"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:243
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:243
msgid ""
"Extracting the upgrade failed. There may be a problem with the network or "
"with the server. "
msgstr ""
"A frissítés kibontása meghiúsult. Probléma lehet a hálózattal vagy a "
"kiszolgálóval. "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:248
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:248
msgid "Verification failed"
msgstr "Az ellenőrzés meghiúsult"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:249
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:249
msgid ""
"Verifying the upgrade failed.  There may be a problem with the network or "
"with the server. "
msgstr ""
"A frissítés ellenőrzése meghiúsult. Probléma lehet a hálózattal vagy a "
"kiszolgálóval. "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:254
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:254
msgid "Authentication failed"
msgstr "Hitelesítés sikertelen"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:255
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:255
msgid ""
"Authenticating the upgrade failed. There may be a problem with the network "
"or with the server. "
msgstr ""
"A frissítés hitelesítése meghiúsult. Probléma lehet a hálózattal vagy a "
"kiszolgálóval. "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:269
#: ../DistUpgrade/DistUpgradeFetcherCore.py:275
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:269
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:275
msgid "Can not run the upgrade"
msgstr "A frissítés nem futtatható!"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:270
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:270
msgid ""
"This usually is caused by a system were /tmp is mounted noexec. Please "
"remount without noexec and run the upgrade again."
msgstr ""
"Ez általában olyan rendszer esetén jelentkezik, amelyen a /tmp kötetet "
"noexec opcióval csatolták. Csatolja újra a kötetet a noexec opció nélkül, "
"majd indítsa el ismét a frissítőt."

#: ../DistUpgrade/DistUpgradeFetcherCore.py:276
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:276
#, python-format
msgid "The error message is '%s'."
msgstr "A hibaüzenet: „%s”."

#: ../DistUpgrade/DistUpgradeViewText.py:89
msgid ""
"Please report this as a bug and include the files /var/log/dist-"
"upgrade/main.log and /var/log/dist-upgrade/apt.log in your report. The "
"upgrade has aborted.\n"
"Your original sources.list was saved in /etc/apt/sources.list.distUpgrade."
msgstr ""
"Jelentse ezt hibaként és a hibajelentéshez mellékelje a /var/log/dist-"
"upgrade/main.log és /var/log/dist-upgrade/apt.log fájlokat. A frissítés "
"megszakadt. Az eredeti sources.list /etc/apt/sources.list.distUpgrade néven "
"került mentésre."

#: ../DistUpgrade/DistUpgradeViewText.py:113
msgid "Aborting"
msgstr "Megszakítás"

#: ../DistUpgrade/DistUpgradeViewText.py:118
msgid "Demoted:\n"
msgstr "Lefokozott:\n"

#: ../DistUpgrade/DistUpgradeViewText.py:151
#: ../DistUpgrade/DistUpgradeViewText.py:189
#: ../DistUpgrade/DistUpgradeViewText.py:196
msgid "Continue [yN] "
msgstr "Folytatja? [i/N] "

#: ../DistUpgrade/DistUpgradeViewText.py:151
#: ../DistUpgrade/DistUpgradeViewText.py:189
msgid "Details [d]"
msgstr "Részletek [r]"

#. TRANSLATORS: the "y" is "yes"
#. TRANSLATORS: first letter of a positive (yes) answer
#: ../DistUpgrade/DistUpgradeViewText.py:155
#: ../DistUpgrade/DistUpgradeViewText.py:199
msgid "y"
msgstr "i"

#. TRANSLATORS: the "n" is "no"
#. TRANSLATORS: first letter of a negative (no) answer
#: ../DistUpgrade/DistUpgradeViewText.py:158
#: ../DistUpgrade/DistUpgradeViewText.py:206
msgid "n"
msgstr "n"

#. TRANSLATORS: the "d" is "details"
#: ../DistUpgrade/DistUpgradeViewText.py:161
msgid "d"
msgstr "r"

#: ../DistUpgrade/DistUpgradeViewText.py:166
#, python-format
msgid "No longer supported: %s\n"
msgstr "Már nem támogatott: %s\n"

#: ../DistUpgrade/DistUpgradeViewText.py:171
#, python-format
msgid "Remove: %s\n"
msgstr "Eltávolítandó: %s\n"

#: ../DistUpgrade/DistUpgradeViewText.py:181
#, python-format
msgid "Install: %s\n"
msgstr "Telepítendő: %s\n"

#: ../DistUpgrade/DistUpgradeViewText.py:186
#, python-format
msgid "Upgrade: %s\n"
msgstr "Frissítendő: %s\n"

#: ../DistUpgrade/DistUpgradeViewText.py:203
msgid "Continue [Yn] "
msgstr "Folytatja? [Y - igen / n - nem] "

#: ../DistUpgrade/DistUpgradeViewText.py:224
msgid ""
"To finish the upgrade, a restart is required.\n"
"If you select 'y' the system will be restarted."
msgstr ""
"A frissítés befejezéséhez a rendszer újraindítása szükséges. \n"
"Az „i” választása esetén a rendszer újraindul."

#: ../DistUpgrade/DistUpgrade.ui.h:1
msgid "    "
msgstr "    "

#: ../DistUpgrade/DistUpgrade.ui.h:2
msgid ""
"<b><big>Cancel the running upgrade?</big></b>\n"
"\n"
"The system could be in an unusable state if you cancel the upgrade. You are "
"strongly adviced to resume the upgrade."
msgstr ""
"<b><big>Megszakítja a folyamatban lévő frissítést?</big></b>\n"
"\n"
"A rendszer használhatatlan állapotban maradhat, ha megszakítja a frissítést. "
"Erősen javasoljuk, hogy folytassa a frissítést."

#: ../DistUpgrade/DistUpgrade.ui.h:5
msgid ""
"<b><big>Restart the system to complete the upgrade</big></b>\n"
"\n"
"Please save your work before continuing."
msgstr ""
"<b><big>A frissítés befejezéséhez újraindítás szükséges</big></b>\n"
"\n"
"Kérem, mentse el munkáját mielőtt folytatná!"

#: ../DistUpgrade/DistUpgrade.ui.h:8
msgid "<b><big>Start the upgrade?</big></b>"
msgstr "<b><big>Megkezdi a frissítést?</big></b>"

#: ../DistUpgrade/DistUpgrade.ui.h:9
msgid "<b><big>Upgrading Ubuntu to version 10.10</big></b>"
msgstr "<b><big>Az Ubuntu frissítése a 10.10-es verzióra</big></b>"

#: ../DistUpgrade/DistUpgrade.ui.h:12
msgid "Difference between the files"
msgstr "Fájlok közti különbség"

#: ../DistUpgrade/DistUpgrade.ui.h:13
msgid "Distribution Upgrade"
msgstr "Disztribúciófrissítés"

#: ../DistUpgrade/DistUpgrade.ui.h:17
msgid "Restarting the computer"
msgstr "A számítógép újraindítása"

#: ../DistUpgrade/DistUpgrade.ui.h:18
msgid "Setting new software channels"
msgstr "Új szoftvercsatornák beállítása"

#: ../DistUpgrade/DistUpgrade.ui.h:19
msgid "Terminal"
msgstr "Terminál"

#: ../DistUpgrade/DistUpgrade.ui.h:20
msgid "_Cancel Upgrade"
msgstr "Frissítés _megszakítása"

#: ../DistUpgrade/DistUpgrade.ui.h:21
msgid "_Continue"
msgstr "_Folytatás"

#: ../DistUpgrade/DistUpgrade.ui.h:23
msgid "_Replace"
msgstr "_Csere"

#: ../DistUpgrade/DistUpgrade.ui.h:24
msgid "_Report Bug"
msgstr "_Hibabejelentés"

#: ../DistUpgrade/DistUpgrade.ui.h:26
msgid "_Resume Upgrade"
msgstr "Frissítés _folytatása"

#: ../DistUpgrade/DistUpgrade.ui.h:27
msgid "_Start Upgrade"
msgstr "Frissítés _indítása"

#: ../UpdateManager/backend/InstallBackendSynaptic.py:54
msgid "Please wait, this can take some time."
msgstr "Kis türelmet, ez eltarthat egy ideig."

#: ../UpdateManager/backend/InstallBackendSynaptic.py:56
msgid "Update is complete"
msgstr "A frissítés befejeződött"

#: ../UpdateManager/DistUpgradeFetcher.py:85
#: ../UpdateManager/DistUpgradeFetcherKDE.py:103
msgid "Could not find the release notes"
msgstr "Nem érhetők el a kiadási megjegyzések"

#: ../UpdateManager/DistUpgradeFetcher.py:86
#: ../UpdateManager/DistUpgradeFetcherKDE.py:104
msgid "The server may be overloaded. "
msgstr "A kiszolgáló túl lehet terhelve. "

#: ../UpdateManager/DistUpgradeFetcher.py:96
#: ../UpdateManager/DistUpgradeFetcherKDE.py:108
msgid "Could not download the release notes"
msgstr "A kiadási megjegyzések nem tölthetők le"

#: ../UpdateManager/DistUpgradeFetcher.py:97
#: ../UpdateManager/DistUpgradeFetcherKDE.py:109
msgid "Please check your internet connection."
msgstr "Kérjük ellenőrizze az internetkapcsolatát."

#: ../UpdateManager/DistUpgradeFetcherKDE.py:62
#: ../UpdateManager/DistUpgradeFetcherKDE.py:85
msgid "Upgrade"
msgstr "Frissítés"

#: ../UpdateManager/DistUpgradeFetcherKDE.py:89
#: ../data/glade/UpdateManager.ui.h:13
#: ../data/glade/UpgradePromptDialog.ui.h:4
msgid "Release Notes"
msgstr "Kiadási megjegyzések"

#: ../UpdateManager/DistUpgradeFetcherKDE.py:128
#: ../UpdateManager/DistUpgradeFetcherKDE.py:141
#: ../UpdateManager/DistUpgradeFetcherKDE.py:143
msgid "Downloading additional package files..."
msgstr "További csomagfájlok letöltése..."

#: ../UpdateManager/DistUpgradeFetcherKDE.py:141
#, python-format
msgid "File %s of %s at %sB/s"
msgstr "%s. fájl, összesen %s. Sebesség: %sB/s"

#: ../UpdateManager/DistUpgradeFetcherKDE.py:143
#, python-format
msgid "File %s of %s"
msgstr "%s. fájl, összesen %s."

#: ../UpdateManager/ChangelogViewer.py:70
msgid "Open Link in Browser"
msgstr "Hivatkozás megnyitása a böngészőben"

#: ../UpdateManager/ChangelogViewer.py:72
msgid "Copy Link to Clipboard"
msgstr "Hivatkozás másolása a vágólapra"

#: ../UpdateManager/GtkProgress.py:161
#, python-format
msgid "Downloading file %(current)li of %(total)li with %(speed)s/s"
msgstr ""
"%(current)li. fájl letöltése, összesen: %(total)li, sebesség: %(speed)s/s"

#: ../UpdateManager/GtkProgress.py:166
#, python-format
msgid "Downloading file %(current)li of %(total)li"
msgstr "%(current)li. fájl letöltése, összesen: %(total)li"

#: ../UpdateManager/UpdateManager.py:326
#, python-format
msgid "Version %s: \n"
msgstr "%s verzió: \n"

#: ../UpdateManager/UpdateManager.py:383
msgid "Downloading list of changes..."
msgstr "Változások listájának letöltése…"

#: ../UpdateManager/UpdateManager.py:423
msgid "_Uncheck All"
msgstr "Kijelölések _törlése"

#: ../UpdateManager/UpdateManager.py:429
msgid "_Check All"
msgstr "Összes _kijelölése"

#: ../UpdateManager/UpdateManager.py:476
#, python-format
msgid "%(count)s update has been selected."
msgid_plural "%(count)s updates have been selected."
msgstr[0] "%(count)s frissítés kiválasztva."
msgstr[1] "%(count)s frissítés kiválasztva."

#: ../UpdateManager/UpdateManager.py:480
#, python-format
msgid "%s will be downloaded."
msgstr "%s kerül letöltésre."

#: ../UpdateManager/UpdateManager.py:491
msgid "The update has already been downloaded, but not installed"
msgid_plural "The updates have already been downloaded, but not installed"
msgstr[0] "A frissítés már le van töltve, de még nincs telepítve"
msgstr[1] "A frissítések már le vannak töltve, de még nincsenek telepítve"

#: ../UpdateManager/UpdateManager.py:495
msgid "There are no updates to install"
msgstr "Nincsenek telepíthető frissítések"

#. TRANSLATORS: this allows to switch the order of the count of
#. updates and the download size string (if needed)
#: ../UpdateManager/UpdateManager.py:500
#, python-format
msgid "%(count_str)s %(download_str)s"
msgstr "%(count_str)s %(download_str)s"

#: ../UpdateManager/UpdateManager.py:507
msgid "Unknown download size."
msgstr "Ismeretlen letöltési méret."

#: ../UpdateManager/UpdateManager.py:518
msgid ""
"It is unknown when the package information was updated last. Please try "
"clicking on the 'Check' button to update the information."
msgstr ""
"Nem ismert, hogy mikor történt a csomaginformációk utolsó frissítése. Az "
"„Ellenőrzés” gombra kattintva frissítheti az információt."

#: ../UpdateManager/UpdateManager.py:527
#, python-format
msgid "The package information was last updated %(days_ago)s day ago."
msgid_plural ""
"The package information was last updated %(days_ago)s days ago."
msgstr[0] "A csomaginformációk %(days_ago)s napja kerültek frissítésre."
msgstr[1] "A csomaginformációk %(days_ago)s napja kerültek frissítésre."

#: ../UpdateManager/UpdateManager.py:531
#, python-format
msgid "The package information was last updated %(hours_ago)s hour ago."
msgid_plural ""
"The package information was last updated %(hours_ago)s hours ago."
msgstr[0] "A csomaginformációk %(hours_ago)s órája kerültek frissítésre."
msgstr[1] "A csomaginformációk %(hours_ago)s órája kerültek frissítésre."

#: ../UpdateManager/UpdateManager.py:535
msgid "The package information was last updated less than one hour ago."
msgstr "A csomaginformációk kevesebb, mint 1 órája kerültek frissítésre."

#: ../UpdateManager/UpdateManager.py:555 ../data/glade/UpdateManager.ui.h:23
msgid ""
"Software updates correct errors, eliminate security vulnerabilities and "
"provide new features."
msgstr ""
"A szoftverfrissítések kijavítják a programhibákat és biztonsági "
"sebezhetőségeket, illetve új szolgáltatásokat biztosítanak."

#: ../UpdateManager/UpdateManager.py:575
msgid "Welcome to Ubuntu"
msgstr "Üdvözli az Ubuntu"

#: ../UpdateManager/UpdateManager.py:576
msgid ""
"These software updates have been issued since Ubuntu was released. If you "
"don't want to install them now, choose \"Update Manager\" from the "
"Administration Menu later."
msgstr ""
"Ezen szoftverfrissítések az Ubuntu kiadása után jelentek meg. Ha ezeket most "
"nem kívánja telepíteni, akkor a későbbiekben válassza a Rendszer → "
"Adminisztráció menü Frissítéskezelő menüpontját."

#: ../UpdateManager/UpdateManager.py:579
msgid "Software updates are available for this computer"
msgstr "Szoftverfrissítések érhetők el a számítógéphez"

#: ../UpdateManager/UpdateManager.py:580
msgid ""
"If you don't want to install them now, choose \"Update Manager\" from the "
"Administration menu later."
msgstr ""
"Ha ezeket most nem kívánja telepíteni, akkor a későbbiekben válassza a "
"Rendszer → Adminisztráció menü Frissítéskezelő menüpontját."

#: ../UpdateManager/UpdateManager.py:629
#, python-format
msgid ""
"The upgrade needs a total of %s free space on disk '%s'. Please free at "
"least an additional %s of disk space on '%s'. Empty your trash and remove "
"temporary packages of former installations using 'sudo apt-get clean'."
msgstr ""
"A frissítéshez %s szabad helyre van szükség a(z) „%s” lemezen. Szabadítson "
"fel még legalább %s helyet a(z) „%s” lemezen. Ürítse ki a Kukát, és "
"távolítsa el a korábbi telepítések ideiglenes csomagjait  a „sudo apt-get "
"clean” parancs használatával."

#: ../UpdateManager/UpdateManager.py:652
msgid ""
"The computer needs to restart to finish installing updates. Please save your "
"work before continuing."
msgstr ""
"A számítógépet újra kell indítani a frissítések telepítésének befejezéséhez. "
"A folytatás előtt mentse munkáját."

#: ../UpdateManager/UpdateManager.py:704
#: ../UpdateManagerHildon/UpdateManagerHildon.py:114
msgid "Reading package information"
msgstr "Csomaginformációk olvasása"

#: ../UpdateManager/UpdateManager.py:719
msgid "Connecting..."
msgstr "Csatlakozás…"

#: ../UpdateManager/UpdateManager.py:729
msgid "You may not be able to check for updates or download new updates."
msgstr "Lehet, hogy nem lehetséges a frissítések keresése vagy telepítése."

#: ../UpdateManager/UpdateManager.py:846
msgid "Could not initialize the package information"
msgstr "A csomaginformációk inicializálása meghiúsult"

#: ../UpdateManager/UpdateManager.py:847
msgid ""
"An unresolvable problem occurred while initializing the package "
"information.\n"
"\n"
"Please report this bug against the 'update-manager' package and include the "
"following error message:\n"
msgstr ""
"Megoldhatatlan probléma lépett fel a csomaginformációk inicializálása "
"közben.\n"
"\n"
"Kérem jelentse a frissítéskezelő hibáját és csatolja a következő "
"hibaüzenetet:\n"

#: ../UpdateManager/UpdateManager.py:871
msgid ""
"An unresolvable problem occurred while calculating the upgrade.\n"
"\n"
"Please report this bug against the 'update-manager' package and include the "
"following error message:"
msgstr "Megoldhatatlan probléma lépett fel a frissítés alatt."

#: ../UpdateManager/UpdateManager.py:896
msgid " (New install)"
msgstr " (Új telepítés)"

#. TRANSLATORS: the b stands for Bytes
#: ../UpdateManager/UpdateManager.py:903
#, python-format
msgid "(Size: %s)"
msgstr "(Méret: %s)"

#: ../UpdateManager/UpdateManager.py:905
#, python-format
msgid "From version %(old_version)s to %(new_version)s"
msgstr "Régi verzió: %(old_version)s, új verzió:  %(new_version)s"

#: ../UpdateManager/UpdateManager.py:909
#, python-format
msgid "Version %s"
msgstr "%s verzió"

#: ../UpdateManager/UpdateManager.py:924
msgid "Your Ubuntu release is not supported anymore"
msgstr "Ez az Ubuntu kiadás már nem támogatott"

#: ../UpdateManager/UpdateManager.py:925
msgid ""
"You will not get any further security fixes or critical updates. Please "
"Upgrade to a later version of Ubuntu Linux."
msgstr ""
"Már nem állnak rendelkezésre biztonsági javítások vagy kritikus frissítések. "
"Frissítsen az Ubuntu Linux egy újabb verziójára."

#: ../UpdateManager/UpdateManager.py:932
msgid "Upgrade information"
msgstr "Frissítési információk"

#: ../UpdateManager/UpdateManager.py:954 ../do-release-upgrade:84
msgid "Release upgrade not possible right now"
msgstr "A kiadás frissítése most nem lehetséges"

#: ../UpdateManager/UpdateManager.py:955 ../do-release-upgrade:85
#, c-format, python-format
msgid ""
"The release upgrade can not be performed currently, please try again later. "
"The server reported: '%s'"
msgstr ""
"A kiadás frissítése jelenleg nem hajtható végre, próbálja újra később. A "
"kiszolgáló üzenete: „%s”"

#: ../UpdateManager/UpdateManager.py:957 ../check-new-release-gtk:85
msgid "Downloading the release upgrade tool"
msgstr "A kiadásfrissítő eszköz letöltése"

#: ../UpdateManager/UpdateManager.py:964
#, python-format
msgid "<b>New Ubuntu release '%s' is available</b>"
msgstr "<b>Elérhető az új „%s” Ubuntu kiadás</b>"

#. we assert a clean cache
#: ../UpdateManager/UpdateManager.py:1003
msgid "Software index is broken"
msgstr "A szoftverindex sérült"

#: ../UpdateManager/UpdateManager.py:1004
msgid ""
"It is impossible to install or remove any software. Please use the package "
"manager \"Synaptic\" or run \"sudo apt-get install -f\" in a terminal to fix "
"this issue at first."
msgstr ""
"Lehetetlen szoftvereket telepíteni vagy törölni. Használja a Synaptic "
"csomagkezelőt vagy futtassa a „sudo apt-get install -f” parancsot egy "
"terminálban a probléma megoldása érdekében."

#: ../UpdateManagerHildon/UpdateManagerHildon.py:136
msgid "Downloading Package Information"
msgstr "Csomaginformációk letöltése"

#: ../UpdateManagerHildon/UpdateManagerHildon.py:137
msgid ""
"The repositories are being checked for new, removed, or updated software "
"packages"
msgstr ""
"Új, eltávolított vagy frissített szoftvercsomagok keresése a tárolókban"

#: ../UpdateManagerHildon/UpdateManagerHildon.py:145
msgid "Downloading Package Updates"
msgstr "Csomagfrissítések letöltése"

#: ../UpdateManagerHildon/UpdateManagerHildon.py:146
msgid ""
"The selected package updates are being downloaded and installed on the system"
msgstr "A kiválasztott csomagfrissítések letöltése és telepítése folyamatban"

#: ../UpdateManagerHildon/UpdateManagerHildon.py:152
msgid "run_synaptic called with unknown action"
msgstr "A run_synaptic függvényt ismeretlen művelet hívta meg"

#: ../UpdateManagerText/UpdateManagerText.py:26
msgid "Cancel"
msgstr "Mégse"

#: ../UpdateManagerText/UpdateManagerText.py:27
msgid "Install"
msgstr "Telepítés"

#: ../UpdateManagerText/UpdateManagerText.py:45
msgid "Building Updates List"
msgstr "Frissítéslista létrehozása"

#: ../UpdateManagerText/UpdateManagerText.py:48
msgid ""
"\n"
"A normal upgrade can not be calculated, please run: \n"
"  sudo apt-get dist-upgrade\n"
"\n"
"\n"
"This can be caused by:\n"
" * A previous upgrade which didn't complete\n"
" * Problems with some of the installed software\n"
" * Unofficial software packages not provided by Ubuntu\n"
" * Normal changes of a pre-release version of Ubuntu"
msgstr ""
"\n"
"Nem sikerült előkészíteni hagyományos frissítést. Futtassa parancssorban a "
"következőt: \n"
"  sudo apt-get dist-upgrade\n"
"\n"
"\n"
"A fenti problémát okozhatta:\n"
" * egy folyamatban lévő frissítés\n"
" * problémák egy telepített programmal\n"
" * nem hivatalos csomagok, amelyeket nem az Ubuntu biztosít\n"
" * szokásos változások egy kiadás előtti Ubuntu verzióban."

#: ../UpdateManagerText/UpdateManagerText.py:117
msgid "Downloading changelog"
msgstr "Változások listájának letöltése"

#: ../UpdateManager/Core/MyCache.py:128
#, python-format
msgid "Other updates (%s)"
msgstr "Egyéb frissítések (%s)"

#: ../UpdateManager/Core/MyCache.py:285
#, python-format
msgid ""
"Changes for the versions:\n"
"%s\n"
"%s\n"
"\n"
msgstr ""
"A következő verziók változásai:\n"
"%s\n"
"%s\n"
"\n"

#: ../UpdateManager/Core/MyCache.py:298
msgid "This change is not coming from a source that supports changelogs."
msgstr "A frissítés forrása nem támogatja a változási naplókat."

#: ../UpdateManager/Core/MyCache.py:304 ../UpdateManager/Core/MyCache.py:324
msgid ""
"Failed to download the list of changes. \n"
"Please check your Internet connection."
msgstr ""
"A módosítások listájának letöltése meghiúsult.\n"
"Ellenőrizze az internetkapcsolatát."

#: ../UpdateManager/Core/MyCache.py:313
#, python-format
msgid ""
"The changelog does not contain any relevant changes.\n"
"\n"
"Please use http://launchpad.net/ubuntu/+source/%s/%s/+changelog\n"
"until the changes become available or try again later."
msgstr ""
"A változások listája nem tartalmaz semmilyen lényeges változást.\n"
"\n"
"Használja a http://launchpad.net/ubuntu/+source/%s/%s/+changelog\n"
"oldalt, míg nem válik hozzáférhetővé, vagy próbálja meg később."

#: ../UpdateManager/Core/MyCache.py:318
#, python-format
msgid ""
"The list of changes is not available yet.\n"
"\n"
"Please use http://launchpad.net/ubuntu/+source/%s/%s/+changelog\n"
"until the changes become available or try again later."
msgstr ""
"A változtatások listája még nem érhető el.\n"
"\n"
"Használja a http://launchpad.net/ubuntu/+source/%s/%s/+changelog\n"
"oldalt, míg nem válik hozzáférhetővé, vagy próbálja meg később."

#: ../UpdateManager/Core/UpdateList.py:52
msgid "Failed to detect distribution"
msgstr "Hiba a kiadás felismerésekor"

#: ../UpdateManager/Core/UpdateList.py:53
#, python-format
msgid "A error '%s' occurred while checking what system you are using."
msgstr "A következő hiba lépett fel a rendszer felmérése során: %s."

#: ../UpdateManager/Core/UpdateList.py:64
msgid "Important security updates"
msgstr "Fontos biztonsági frissítések"

#: ../UpdateManager/Core/UpdateList.py:65
msgid "Recommended updates"
msgstr "Ajánlott frissítések"

#: ../UpdateManager/Core/UpdateList.py:66
msgid "Proposed updates"
msgstr "Javasolt frissítések"

#: ../UpdateManager/Core/UpdateList.py:67
msgid "Backports"
msgstr "Visszaportolt csomagok"

#: ../UpdateManager/Core/UpdateList.py:68
msgid "Distribution updates"
msgstr "Disztribúciófrissítések"

#: ../UpdateManager/Core/UpdateList.py:73
msgid "Other updates"
msgstr "Egyéb frissítések"

#: ../UpdateManager/Core/UpdateList.py:82
msgid "Previous selected"
msgstr "Előző kijelölés"

#: ../data/glade/UpdateManager.ui.h:1
msgid ""
"<b><big>You must check for updates manually</big></b>\n"
"\n"
"Your system does not check for updates automatically. You can configure this "
"behavior in <i>Software Sources</i> on the <i>Updates</i> tab."
msgstr ""
"<b><big>Saját kezűleg kell frissítenie a rendszert</big></b>\n"
"\n"
"A rendszere jelenleg nem keresi automatikusan a frissítéseket. Ezt a "
"viselkedést a <i>Szoftverforrások</i> ablak <i>Frissítések</i> lapján "
"változtathatja meg."

#: ../data/glade/UpdateManager.ui.h:4
msgid "<big><b>Not all updates can be installed</b></big>"
msgstr "<big><b>Nem minden frissítés telepíthető</b></big>"

#: ../data/glade/UpdateManager.ui.h:5
msgid "<big><b>Running on battery</b></big>"
msgstr "<big><b>A rendszer akkumulátorról működik</b></big>"

#: ../data/glade/UpdateManager.ui.h:6
msgid "<big><b>Starting Update Manager</b></big>"
msgstr "<big><b>Frissítéskezelő indítása</b></big>"

#: ../data/glade/UpdateManager.ui.h:7
msgid "Changes"
msgstr "Módosítások"

#: ../data/glade/UpdateManager.ui.h:8
msgid "Chec_k"
msgstr "_Ellenőrzés"

#: ../data/glade/UpdateManager.ui.h:9
msgid "Co_ntinue"
msgstr "_Folytatás"

#: ../data/glade/UpdateManager.ui.h:10
msgid "Description"
msgstr "Leírás"

#: ../data/glade/UpdateManager.ui.h:11
msgid "Description of update"
msgstr "Frissítés leírása"

#: ../data/glade/UpdateManager.ui.h:12
msgid ""
"It&#x2019;s safer to connect the computer to AC power before updating."
msgstr ""
"Biztonságosabb, ha hálózati tápellátásra köti a számítógépet a frissítés "
"megkezdése előtt."

#: ../data/glade/UpdateManager.ui.h:14
msgid ""
"Run a partial upgrade, to install as many updates as possible. \n"
"\n"
"This can be caused by:\n"
" * A previous upgrade which didn't complete\n"
" * Problems with some of the installed software\n"
" * Unofficial software packages not provided by Ubuntu\n"
" * Normal changes of a pre-release version of Ubuntu"
msgstr ""
"Futtasson intelligens frissítést a lehető legtöbb frissítés telepítése "
"érdekében. Ezt\n"
"\n"
" * egy korábbi befejezetlen frissítés;\n"
" * egyes telepített szoftverekkel kapcsolatos problémák;\n"
" * nem hivatalos, nem az Ubuntu által szállított szoftvercsomagok vagy\n"
" * az Ubuntu fejlesztői verziójának normális változásai okozhatják."

#: ../data/glade/UpdateManager.ui.h:21
msgid "Settings..."
msgstr "Beállítások..."

#: ../data/glade/UpdateManager.ui.h:22
#: ../data/glade/UpgradePromptDialog.ui.h:5
msgid "Show progress of individual files"
msgstr "Egyes fájlok állapotának mutatása"

#: ../data/glade/UpdateManager.ui.h:24
msgid "Starting Update Manager"
msgstr "Frissítéskezelő indítása"

#: ../data/glade/UpdateManager.ui.h:25
msgid "U_pgrade"
msgstr "_Frissítés"

#: ../data/glade/UpdateManager.ui.h:26 ../data/update-manager.desktop.in.h:3
#: ../data/update-manager-hildon.desktop.in.h:3
msgid "Update Manager"
msgstr "Frissítéskezelő"

#: ../data/glade/UpdateManager.ui.h:27
msgid "Your system is running on battery. Are you sure you want to continue?"
msgstr "A rendszere akkumulátorról működik. Biztos, hogy folytatni kívánja?"

#: ../data/glade/UpdateManager.ui.h:28
msgid "_Hide this information in the future"
msgstr "_A jövőben ne mutassa ezt az információt"

#: ../data/glade/UpdateManager.ui.h:29
msgid "_Install Updates"
msgstr "_Telepítés"

#: ../data/glade/UpdateManager.ui.h:30
msgid "_Partial Upgrade"
msgstr "_Intelligens frissítés"

#: ../data/glade/UpdateManager.ui.h:32
msgid "_Upgrade"
msgstr "_Frissítés"

#: ../data/glade/UpdateManager.ui.h:33
msgid "updates"
msgstr "frissítés"

#: ../data/glade/UpgradePromptDialog.ui.h:1
msgid ""
"<b>A new version of Ubuntu is available. Would you like to upgrade?</b>"
msgstr "<b>Elérhető az Ubuntu egy új változata. Szeretné frissíteni?</b>"

#: ../data/glade/UpgradePromptDialog.ui.h:2
msgid "Ask Me Later"
msgstr "Kérdezzen rá később"

#: ../data/glade/UpgradePromptDialog.ui.h:3
msgid "Don't Upgrade"
msgstr "Ne frissítse"

#: ../data/glade/UpgradePromptDialog.ui.h:6
msgid "Yes, Upgrade Now"
msgstr "Igen, frissítse most"

#: ../data/glade/UpgradePromptDialog.ui.h:7
msgid ""
"You can upgrade at a later time by opening Update Manager and click on "
"\"Upgrade\"."
msgstr ""
"Később is végrehajthatja a frissítést a Frissítéskezelő megnyitásával és a "
"„Frissítés” gomb megnyomásával."

#: ../data/glade/UpgradePromptDialog.ui.h:8
msgid "You have declined to upgrade to the new Ubuntu"
msgstr "Ön elutasította az Ubuntu új változatára történő frissítést."

#: ../data/update-manager.desktop.in.h:1
#: ../data/update-manager-hildon.desktop.in.h:1
msgid "Show and install available updates"
msgstr "Rendelkezésre álló frissítések megjelenítése és telepítése"

#: ../data/update-manager.desktop.in.h:2
#: ../data/update-manager-hildon.desktop.in.h:2
msgid "Software Updates"
msgstr "Szoftverfrissítések"

#: ../data/update-manager.schemas.in.h:1
msgid "*deprecated* Check for new distribution releases"
msgstr "Új disztribúciókiadások keresése (elavult)"

#: ../data/update-manager.schemas.in.h:2
msgid "Auto close the install window after successful install"
msgstr "A telepítőablak automatikus bezárása sikeres telepítés esetén"

#: ../data/update-manager.schemas.in.h:3
msgid "First run welcome message"
msgstr "Üdvözlőszöveg (csak az első futáskor jelenik meg)"

#: ../data/update-manager.schemas.in.h:4
msgid ""
"If automatic checking for updates is disabled, you have to reload the "
"channel list manually. This option allows to hide the reminder shown in this "
"case."
msgstr ""
"Ha a frissítések automatikus keresése le van tiltva, akkor a csatornalistát "
"kézzel kell újratölteni. Ezzel a beállítással elrejtheti az ilyen "
"helyzetekben megjelenő emlékeztetőt."

#: ../data/update-manager.schemas.in.h:5
msgid "If this key is set a first run welcome message will be presented."
msgstr "E kulcs igazra állításával megjeleníthető az üdvözlőszöveg."

#: ../data/update-manager.schemas.in.h:6
msgid ""
"If this key is set the install window will be automatically closed on "
"successful installation."
msgstr ""
"Ha ez a kulcs be van állítva, akkor a telepítőablak sikeres telepítések után "
"automatikusan bezárul."

#: ../data/update-manager.schemas.in.h:7
msgid ""
"If this key is set the main update list window will show version information "
"(from version to version)."
msgstr ""
"Ha ez a kulcs be van állítva, a fő frissítési ablakban meg fog jelenni a "
"verzióinformáció (hogy melyik verzióról melyikre frissít)."

#: ../data/update-manager.schemas.in.h:8
msgid ""
"If this key is set, the main update list window will show the package "
"summary before the package name."
msgstr ""
"Ha ez a kulcs be van állítva, akkor a fő frissítéslista ablak megjeleníti a "
"csomag összefoglalását a csomagnév előtt."

#: ../data/update-manager.schemas.in.h:9
msgid "Remind to reload the channel list"
msgstr "Figyelmeztessen, ha újra kell tölteni a csatornalistát"

#: ../data/update-manager.schemas.in.h:10
msgid "Show details of an update"
msgstr "Frissítés részleteinek megjelenítése"

#: ../data/update-manager.schemas.in.h:11
msgid "Show package summary before package name in update list"
msgstr ""
"Csomag összefoglalásának megjelenítése a csomagnév előtt a frissítéslistában"

#: ../data/update-manager.schemas.in.h:12
msgid "Show version in update list"
msgstr "Verzió megjelenítése a frissítési listában"

#: ../data/update-manager.schemas.in.h:13
msgid "Stores the size of the update-manager dialog"
msgstr "A frissítéskezelő ablak méretének tárolása"

#: ../data/update-manager.schemas.in.h:14
msgid ""
"Stores the state of the expander that contains the list of changes and the "
"description"
msgstr ""
"Eltárolja a módosítások listáját és a leírást tartalmazó kiterjesztő "
"állapotát"

#: ../data/update-manager.schemas.in.h:15
msgid "The window size"
msgstr "Az ablak mérete"

#: ../data/update-manager.schemas.in.h:16
msgid ""
"This key is deprecated in favor of the file /etc/update-manager/release-"
"upgrades Check automatically if a new version of the current distribution is "
"available and offer to upgrade (if possible)."
msgstr ""
"Ez a kulcs elavult, helyette az /etc/update-manager/release-upgrades fájl "
"használatos. Az aktuális terjesztés új verziójának automatikus keresése és a "
"frissítés felajánlása (ha lehetséges)."

#: ../data/update-manager.schemas.in.h:17
msgid ""
"This will permanently hide the new release prompt from check-new-release-"
"gtk. Note that the small button in the main update-manager UI will still be "
"there."
msgstr ""
"Ez véglegesen elrejti az új kiadás kérdést a „check-new-release-gtk” "
"alkalmazásból. Ne feledje, hogy a Frissítéskezelőben továbbra is "
"megtalálható lesz ez a gomb."

#: ../data/update-manager.schemas.in.h:18
msgid "make check-new-release-gtk ignore a given new release"
msgstr "A check-new-release-gtk hagyjon figyelmen kívül egy adott új kiadást"

#: ../update-manager:53 ../do-release-upgrade:33
msgid "Show version and exit"
msgstr "Verziószám kiírása és kilépés"

#: ../update-manager:56
msgid "Directory that contains the data files"
msgstr "Az adatfájlokat tartalmazó könyvtár"

#: ../update-manager:59
msgid "Check if a new Ubuntu release is available"
msgstr "Új Ubuntu kiadás elérhetőségének ellenőrzése"

#: ../update-manager:62 ../do-release-upgrade:36 ../check-new-release-gtk:136
msgid "Check if upgrading to the latest devel release is possible"
msgstr ""
"Ellenőrzi, hogy lehetséges-e frissíteni a legújabb fejlesztői kiadásra"

#: ../update-manager:66
msgid "Upgrade using the latest proposed version of the release upgrader"
msgstr ""
"Frissítés a kiadásfrissítő legújabb ajánlott változatának segítségével"

#: ../update-manager:73
msgid "Do not focus on map when starting"
msgstr "Ne kerüljön fókuszba indításkor"

#: ../update-manager:76
msgid "Try to run a dist-upgrade"
msgstr "Kísérlet disztribúciófrissítés futtatására"

#: ../update-manager:80 ../do-release-upgrade:52
msgid "Test upgrade with a sandbox aufs overlay"
msgstr "Tesztfrissítés tesztkörnyezetben aufs használatával"

#: ../update-manager:100
msgid "Running partial upgrade"
msgstr "Intelligens frissítés futtatása"

#: ../do-release-upgrade:40 ../check-new-release-gtk:140
msgid ""
"Try upgrading to the latest release using the upgrader from $distro-proposed"
msgstr ""
"Kísérlet a legfrissebb kiadásra való áttérésre $distro-proposed kiadásról a "
"frissítő használatával"

#: ../do-release-upgrade:44
msgid ""
"Run in a special upgrade mode.\n"
"Currently 'desktop' for regular upgrades of a desktop system and 'server' "
"for server systems are supported."
msgstr ""
"Futtatás speciális frissítő módban.\n"
"Jelenleg a „desktop” (asztali rendszerek szabályos frissítése) és a „server” "
"(kiszolgálórendszerek frissítése) módok támogatottak."

#: ../do-release-upgrade:50
msgid "Run the specified frontend"
msgstr "A megadott előtét futtatása"

#: ../do-release-upgrade:55
msgid ""
"Check only if a new distribution release is available and report the result "
"via the exit code"
msgstr ""
"Csak akkor ellenőrizze, ha egy új kiadás elérhetővé válik, az eredményt "
"jelenítse meg a kimeneti értékben"

#: ../do-release-upgrade:69
msgid "Checking for a new ubuntu release"
msgstr "Új Ubuntu-kiadás keresése"

#: ../do-release-upgrade:79
msgid "No new release found"
msgstr "Nem található új kiadás"

#: ../do-release-upgrade:91
#, c-format
msgid "New release '%s' available."
msgstr "Elérhető az új „%s” kiadás."

#: ../do-release-upgrade:92
msgid "Run 'do-release-upgrade' to upgrade to it."
msgstr "A frissítéshez futassa a „do-release-upgrade” parancsot."

#: ../check-new-release-gtk:65
msgid "Ubuntu %(version)s Upgrade Available"
msgstr "Ubuntu %(version)s frissítés érhető el"

#: ../check-new-release-gtk:101
#, c-format
msgid "You have declined the upgrade to Ubuntu %s"
msgstr "Ön elutasította az Ubuntu %s kiadásra történő frissítést"

#: ../Janitor/computerjanitor/exc.py:30
#, python-format
msgid "Unimplemented method: %s"
msgstr "Megvalósítatlan metódus: %s"

#: ../Janitor/computerjanitor/file_cruft.py:46
msgid "A file on disk"
msgstr "Egy fájl a lemezen"

#: ../Janitor/computerjanitor/package_cruft.py:45
msgid ".deb package"
msgstr ".deb csomag"

#: ../Janitor/computerjanitor/missing_package_cruft.py:33
msgid "Install missing package."
msgstr "Hiányzó csomag telepítése."

#: ../Janitor/computerjanitor/missing_package_cruft.py:42
#, python-format
msgid "Package %s should be installed."
msgstr "A(z) %s csomagot telepíteni kell."

#. pragma: no cover
#: ../Janitor/plugins/dpkg_status_plugin.py:36
#, python-format
msgid "%i obsolete entries in the status file"
msgstr "%i elavult bejegyzés van az állapotfájlban"

#: ../Janitor/plugins/dpkg_status_plugin.py:39
msgid "Obsolete entries in dpkg status"
msgstr "Elavult bejegyzések a dpkg állapotban"

#. pragma: no cover
#: ../Janitor/plugins/dpkg_status_plugin.py:42
msgid "Obsolete dpkg status entries"
msgstr "Elavult dpkg állapotbejegyzések"

#: ../Janitor/plugins/kdelibs4to5_plugin.py:39
msgid ""
"When upgrading, if kdelibs4-dev is installed, kdelibs5-dev needs to be "
"installed. See bugs.launchpad.net, bug #279621 for details."
msgstr ""
"Frissítéskor, ha a kdelibs4-dev telepítve van, a kdelibs5-dev csomagot is "
"telepíteni kell. Részletekért lásd a bugs.launchpad.net #279621 számú "
"hibáját."

#: ../Janitor/plugins/langpack_manual_plugin.py:34
#, python-format
msgid "%s needs to be marked as manually installed."
msgstr "A(z) %s csomagot saját kezűleg telepítettként kell megjelölni."

#: ../Janitor/plugins/remove_lilo_plugin.py:28
msgid ""
"Remove lilo since grub is also installed.(See bug #314004 for details.)"
msgstr ""
"A lilo eltávolítása, mivel a grub is telepítve van. (Lásd a #314004 számú "
"hibát a részletekért)."

#~ msgid "Unknown download size"
#~ msgstr "A letöltés mérete ismeretlen"

#, python-format
#~ msgid "<b>Downgrade %s</b>"
#~ msgstr "<b>%s visszafejlesztése</b>"

#~ msgid "Support for some applications ended"
#~ msgstr "Egyes alkalmazások támogatása megszűnt"

#~ msgid ""
#~ "The upgrade is now aborted. Your system could be in an unusable state. A "
#~ "recovery will run now (dpkg --configure -a)."
#~ msgstr ""
#~ "A frissítés most megszakadt. Előfordulhat, hogy a rendszer használhatatlan "
#~ "állapotban van. Egy helyreállítás kerül futtatásra (dpkg --configure -a)."

#~ msgid ""
#~ "The upgrade is now aborted. Please check your Internet connection or "
#~ "installation media and try again. All files downloaded so far are kept."
#~ msgstr ""
#~ "A frissítés most megszakadt. Ellenőrizze internetkapcsolatát vagy a "
#~ "telepítőlemezt és próbálja újra. Minden eddig letöltött fájl megmarad."

#, python-format
#~ msgid ""
#~ "The upgrade is now aborted. The upgrade needs a total of %s free space on "
#~ "disk '%s'. Please free at least an additional %s of disk space on '%s'. "
#~ "Empty your trash and remove temporary packages of former installations using "
#~ "'sudo apt-get clean'."
#~ msgstr ""
#~ "A frissítés most megszakadt. A frissítéshez %s szabad hely szükséges a(z) "
#~ "„%s” lemezen. Szabadítson fel további %s lemezterületet a(z) „%s” eszközön. "
#~ "Ürítse a Kukát és törölje a korábbi telepítések átmeneti fájljait a „sudo "
#~ "apt-get clean” parancs kiadásával."

#~ msgid ""
#~ "The upgrade is now aborted. Please check your Internet connection or "
#~ "installation media and try again. "
#~ msgstr ""
#~ "A frissítés most megszakadt. Ellenőrizze internetkapcsolatát vagy a "
#~ "telepítőlemezt és próbálja újra. "

#~ msgid ""
#~ "Please report this as a bug and include the files /var/log/dist-"
#~ "upgrade/main.log and /var/log/dist-upgrade/apt.log in your report. The "
#~ "upgrade is now aborted.\n"
#~ "Your original sources.list was saved in /etc/apt/sources.list.distUpgrade."
#~ msgstr ""
#~ "Jelentse ezt hibaként és a hibajelentéshez mellékelje a /var/log/dist-"
#~ "upgrade/main.log és /var/log/dist-upgrade/apt.log fájlokat. A frissítés most "
#~ "megszakadt.\n"
#~ "Az eredeti sources.list /etc/apt/sources.list.distUpgrade néven került "
#~ "mentésre."

#~ msgid ""
#~ "Please report this as a bug (if you haven't already) and include the files "
#~ "/var/log/dist-upgrade/main.log and /var/log/dist-upgrade/apt.log in your "
#~ "report. The upgrade is now aborted.\n"
#~ "Your original sources.list was saved in /etc/apt/sources.list.distUpgrade."
#~ msgstr ""
#~ "Jelentse ezt a hibát (ha eddig még nem tette volna) és csatolja a "
#~ "/var/log/dist-upgrade/main.log és /var/log/dist-upgrade/apt.log nevű "
#~ "fájlokat. A frissítés most megszakadt.\n"
#~ "Az eredeti sources.list /etc/apt/sources.list.distUpgrade néven került "
#~ "mentésre."

#~ msgid "Restart _Later"
#~ msgstr "Újraindítás _később"

#, python-format
#~ msgid ""
#~ "Download size: %s\n"
#~ "%s selected."
#~ msgstr ""
#~ "Letöltendő adatmennyiség: %s\n"
#~ "%s kiválasztva."

#, python-format
#~ msgid "The package information was last updated %s hour ago."
#~ msgid_plural "The package information was last updated %s hours ago."
#~ msgstr[0] "A csomaginformációk %s órája kerültek frissítésre."
#~ msgstr[1] "A csomaginformációk %s órája kerültek frissítésre."

#, python-format
#~ msgid "The package information was last updated %s day ago."
#~ msgid_plural "The package information was last updated %s days ago."
#~ msgstr[0] "A csomaginformációk %s nappal ezelőtt kerültek frissítésre."
#~ msgstr[1] "A csomaginformációk %s nappal ezelőtt kerültek frissítésre."

#~ msgid "<b><big>Upgrading Ubuntu to version 10.04 LTS</big></b>"
#~ msgstr "<b><big>Frissítés az Ubuntu 10.04 LTS verziójára</big></b>"

#~ msgid ""
#~ "Canonical Ltd. no longer provides support for the following software "
#~ "packages. You can still get support from the community."
#~ msgstr ""
#~ "A Canonical Ltd. már nem támogatja az alábbi szoftvercsomagokat. A "
#~ "közösségtől továbbra is kaphat támogatást."

#~ msgid ""
#~ "Canonical Ltd. no longer provides support for the following software "
#~ "packages. You can still get support from the community.\n"
#~ "\n"
#~ "These packages will be suggested for removal at the end of the upgrade "
#~ "because you have not enabled the community maintained software channel "
#~ "(universe)."
#~ msgstr ""
#~ "A Canonical Ltd. már nem támogatja az alábbi szoftvercsomagokat. A "
#~ "közösségtől továbbra is kaphat támogatást.\n"
#~ "\n"
#~ "A frissítés végén ezen csomagok eltávolításra kerülnek, mivel nem "
#~ "engedélyezte a közösség által karbantartott szoftvercsatornát (universe)."
