# Russian translation for update-manager
# Copyright (c) (c) 2006 Canonical Ltd, and Rosetta Contributors 2006
# This file is distributed under the same license as the update-manager package.
# Igor Zubarev <igor4u@gmail.com>, 2006.
#
msgid ""
msgstr ""
"Project-Id-Version: update-manager\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2010-09-22 05:12+0000\n"
"PO-Revision-Date: 2010-09-25 05:22+0000\n"
"Last-Translator: Sergey Sedov <sedov@webmail.perm.ru>\n"
"Language-Team: Russian <ru@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=3; plural=n%10==1 && n%100!=11 ? 0 : n%10>=2 && "
"n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2;\n"
"X-Launchpad-Export-Date: 2010-09-27 08:04+0000\n"
"X-Generator: Launchpad (build Unknown)\n"

#. TRANSLATORS: download size is 0
#: ../DistUpgrade/utils.py:346 ../UpdateManager/Core/utils.py:346
msgid "0 KB"
msgstr "0 КБ"

#. TRANSLATORS: download size of very small updates
#: ../DistUpgrade/utils.py:349 ../UpdateManager/Core/utils.py:349
msgid "1 KB"
msgstr "1 КБ"

#. TRANSLATORS: download size of small updates, e.g. "250 KB"
#: ../DistUpgrade/utils.py:352 ../UpdateManager/Core/utils.py:352
#, python-format
msgid "%.0f KB"
msgstr "%.0f КБ"

#. TRANSLATORS: download size of updates, e.g. "2.3 MB"
#: ../DistUpgrade/utils.py:355 ../UpdateManager/Core/utils.py:355
#, python-format
msgid "%.1f MB"
msgstr "%.1f МБ"

#. TRANSLATORS: %s is a country
#: ../DistUpgrade/distro.py:209 ../DistUpgrade/distro.py:424
#, python-format
msgid "Server for %s"
msgstr "Сервер для %s"

#. More than one server is used. Since we don't handle this case
#. in the user interface we set "custom servers" to true and
#. append a list of all used servers
#: ../DistUpgrade/distro.py:227 ../DistUpgrade/distro.py:233
#: ../DistUpgrade/distro.py:249
msgid "Main server"
msgstr "Основной сервер"

#: ../DistUpgrade/distro.py:253
msgid "Custom servers"
msgstr "Свои сервера"

#: ../DistUpgrade/DistUpgradeAptCdrom.py:131
msgid "Could not calculate sources.list entry"
msgstr "Не удалось рассчитать элемент sources.list"

#: ../DistUpgrade/DistUpgradeAptCdrom.py:234
msgid ""
"Unable to locate any package files, perhaps this is not a Ubuntu Disc or the "
"wrong architecture?"
msgstr ""
"Не удалось найти файлы пакетов, может быть, это не диск дистрибутива Ubuntu "
"или неверная архитектура?"

#: ../DistUpgrade/DistUpgradeAptCdrom.py:277
msgid "Failed to add the CD"
msgstr "Не удалось добавить компакт-диск"

#: ../DistUpgrade/DistUpgradeAptCdrom.py:278
#, python-format
msgid ""
"There was a error adding the CD, the upgrade will abort. Please report this "
"as a bug if this is a valid Ubuntu CD.\n"
"\n"
"The error message was:\n"
"'%s'"
msgstr ""
"При добавлении компакт-диска произошла ошибка, обновление будет прервано. "
"Пожалуйста, сообщите об ошибке, если это был корректный компакт-диск "
"Ubuntu.\n"
"\n"
"Сообщение об ошибке:\n"
"'%s'"

#: ../DistUpgrade/DistUpgradeCache.py:130
msgid "Remove package in bad state"
msgid_plural "Remove packages in bad state"
msgstr[0] "Удалить пакет, помеченный как ошибочный"
msgstr[1] "Удалить пакеты, помеченные как ошибочные"
msgstr[2] "Удалить пакеты, помеченные как ошибочные"

#: ../DistUpgrade/DistUpgradeCache.py:133
#, python-format
msgid ""
"The package '%s' is in an inconsistent state and needs to be reinstalled, "
"but no archive can be found for it. Do you want to remove this package now "
"to continue?"
msgid_plural ""
"The packages '%s' are in an inconsistent state and need to be reinstalled, "
"but no archives can be found for them. Do you want to remove these packages "
"now to continue?"
msgstr[0] ""
"Пакет '%s' является несовместимым и его надо переустановить, однако его "
"архивный файл отсутствует. Желаете ли вы сейчас удалить этот пакет для "
"продолжения?"
msgstr[1] ""
"Пакеты '%s' являются несовместимыми и их надо переустановить, однако их "
"архивные файлы отсутствуют. Желаете ли вы сейчас удалить эти пакеты для "
"продолжения?"
msgstr[2] ""
"Пакеты '%s' являются несовместимыми и их надо переустановить, однако их "
"архивные файлы отсутствуют. Желаете ли вы сейчас удалить эти пакеты для "
"продолжения?"

#. FIXME: not ideal error message, but we just reuse a
#. existing one here to avoid a new string
#: ../DistUpgrade/DistUpgradeCache.py:231
msgid "The server may be overloaded"
msgstr "Возможно сервер перегружен"

#: ../DistUpgrade/DistUpgradeCache.py:341
msgid "Broken packages"
msgstr "Повреждённые пакеты"

#: ../DistUpgrade/DistUpgradeCache.py:342
msgid ""
"Your system contains broken packages that couldn't be fixed with this "
"software. Please fix them first using synaptic or apt-get before proceeding."
msgstr ""
"Система содержит повреждённые пакеты, которые не могут быть исправлены "
"данной программой. Пожалуйста, исправьте их, используя synaptic или apt-get, "
"прежде чем продолжить."

#. FIXME: change the text to something more useful
#: ../DistUpgrade/DistUpgradeCache.py:631
#, python-format
msgid ""
"An unresolvable problem occurred while calculating the upgrade:\n"
"%s\n"
"\n"
" This can be caused by:\n"
" * Upgrading to a pre-release version of Ubuntu\n"
" * Running the current pre-release version of Ubuntu\n"
" * Unofficial software packages not provided by Ubuntu\n"
"\n"
msgstr ""
"При расчёте обновления произошла неразрешимая ошибка:\n"
"%s\n"
"\n"
" Это может быть вызвано:\n"
" * Обновлением к пред-релизной версии Ubuntu\n"
" * Запуском данной пред-релизной версии Ubuntu\n"
" * Неофициальным программным обеспечением, которое не поддерживается Ubuntu\n"
"\n"

#: ../DistUpgrade/DistUpgradeCache.py:641
msgid "This is most likely a transient problem, please try again later."
msgstr "Вероятно, это временная проблема. Попробуйте повторить позднее."

#: ../DistUpgrade/DistUpgradeCache.py:644
msgid ""
"If none of this applies, then please report this bug against the 'update-"
"manager' package and include the files in /var/log/dist-upgrade/ in the bug "
"report."
msgstr ""
"Если ничего не помогает, сообщите, пожалуйста, об ошибке, связанной с "
"пакетом \"update-manager\", и приложите файлы из /var/log/dist-upgrade/ к "
"сообщению."

#: ../DistUpgrade/DistUpgradeCache.py:650
#: ../UpdateManager/UpdateManager.py:870
msgid "Could not calculate the upgrade"
msgstr "Не удалось рассчитать обновление системы"

#: ../DistUpgrade/DistUpgradeCache.py:700
msgid "Error authenticating some packages"
msgstr "Ошибка при проверке подлинности некоторых пакетов"

#: ../DistUpgrade/DistUpgradeCache.py:701
msgid ""
"It was not possible to authenticate some packages. This may be a transient "
"network problem. You may want to try again later. See below for a list of "
"unauthenticated packages."
msgstr ""
"Не удалось проверить подлинность некоторых пакетов. Возможно, это "
"кратковременная проблема с сетью и стоит повторить операцию позже. Ниже "
"приведен список пакетов, не прошедших проверку."

#: ../DistUpgrade/DistUpgradeCache.py:721
#, python-format
msgid ""
"The package '%s' is marked for removal but it is in the removal blacklist."
msgstr ""
"Пакет '%s' отмечен для удаления, но он находится в списке запрещённых к "
"удалению."

#: ../DistUpgrade/DistUpgradeCache.py:725
#, python-format
msgid "The essential package '%s' is marked for removal."
msgstr "Основной пакет '%s' отмечен для удаления."

#: ../DistUpgrade/DistUpgradeCache.py:734
#, python-format
msgid "Trying to install blacklisted version '%s'"
msgstr "Попытка установки внесённой в чёрный список версии '%s'"

#: ../DistUpgrade/DistUpgradeCache.py:836
#, python-format
msgid "Can not mark '%s' for upgrade"
msgstr "Не удается отметить '%s' для обновления"

#: ../DistUpgrade/DistUpgradeCache.py:850
#, python-format
msgid "Can't install '%s'"
msgstr "Не удалось установить «%s»"

#: ../DistUpgrade/DistUpgradeCache.py:851
msgid ""
"It was impossible to install a required package. Please report this as a "
"bug. "
msgstr ""
"Не удалось установить необходимый пакет. Пожалуйста, отправьте отчёт об "
"ошибке. "

#. FIXME: provide a list
#: ../DistUpgrade/DistUpgradeCache.py:860
msgid "Can't guess meta-package"
msgstr "Не удалось подобрать мета-пакет"

#: ../DistUpgrade/DistUpgradeCache.py:861
msgid ""
"Your system does not contain a ubuntu-desktop, kubuntu-desktop, xubuntu-"
"desktop or edubuntu-desktop package and it was not possible to detect which "
"version of Ubuntu you are running.\n"
" Please install one of the packages above first using synaptic or apt-get "
"before proceeding."
msgstr ""
"Ваша система не содержит пакетов ubuntu-desktop, kubuntu-desktop, xubuntu-"
"desktop или edubuntu-desktop, и поэтому невозможно определить, какая версия "
"Ubuntu у вас запущена.\n"
" Пожалуйста, установите сначала один из этих пакетов с помощью synaptic или "
"apt-get перед продолжением."

#: ../DistUpgrade/DistUpgradeController.py:86
msgid "Reading cache"
msgstr "Чтение кеша"

#: ../DistUpgrade/DistUpgradeController.py:189
msgid "Unable to get exclusive lock"
msgstr "Не удалось получить исключительную блокировку"

#: ../DistUpgrade/DistUpgradeController.py:190
msgid ""
"This usually means that another package management application (like apt-get "
"or aptitude) already running. Please close that application first."
msgstr ""
"Как правило, это означает, что уже запущена другая программа управления "
"пакетами (например, apt-get или aptitude). Пожалуйста, закройте эту "
"программу, чтобы продолжить."

#: ../DistUpgrade/DistUpgradeController.py:236
msgid "Upgrading over remote connection not supported"
msgstr "Обновление через удалённое соединение не поддерживается"

#: ../DistUpgrade/DistUpgradeController.py:237
msgid ""
"You are running the upgrade over a remote ssh connection with a frontend "
"that does not support this. Please try a text mode upgrade with 'do-release-"
"upgrade'.\n"
"\n"
"The upgrade will abort now. Please try without ssh."
msgstr ""
"Вы пытаетесь выполнить обновление через ssh-соединение с неподдерживаемым "
"клиентом. Обновитесь в текстовом режиме через \"do-release-upgrade\".\n"
"\n"
"Обновление остановлено. Попробуйте без ssh."

#: ../DistUpgrade/DistUpgradeController.py:251
msgid "Continue running under SSH?"
msgstr "Продолжить работу через SSH?"

#: ../DistUpgrade/DistUpgradeController.py:252
#, python-format
msgid ""
"This session appears to be running under ssh. It is not recommended to "
"perform a upgrade over ssh currently because in case of failure it is harder "
"to recover.\n"
"\n"
"If you continue, an additional ssh daemon will be started at port '%s'.\n"
"Do you want to continue?"
msgstr ""
"Этот сеанс запущен через ssh. Не рекомендуется выполнять обновление через "
"ssh, так как в случае неудачи восстановление будет очень сложным.\n"
"\n"
"Если вы продолжите, дополнительная служба ssh будет запущена на порту "
"\"%s\".\n"
"Хотите ли вы продолжить?"

#: ../DistUpgrade/DistUpgradeController.py:267
msgid "Starting additional sshd"
msgstr "Запускается дополнительный sshd"

#: ../DistUpgrade/DistUpgradeController.py:268
#, python-format
msgid ""
"To make recovery in case of failure easier, an additional sshd will be "
"started on port '%s'. If anything goes wrong with the running ssh you can "
"still connect to the additional one.\n"
msgstr ""
"Чтобы сделать восстановление легче в случае ошибки, дополнительная служба "
"sshd будет запущена на порту '%s'. Если что-либо случится, с помощью ssh вы "
"сможете подключиться к данной службе.\n"

#: ../DistUpgrade/DistUpgradeController.py:339
#: ../DistUpgrade/DistUpgradeController.py:384
msgid "Can not upgrade"
msgstr "Не удалось обновить"

#: ../DistUpgrade/DistUpgradeController.py:340
#, python-format
msgid "An upgrade from '%s' to '%s' is not supported with this tool."
msgstr "Обновление от '%s' к '%s' не поддерживается этой утилитой."

#: ../DistUpgrade/DistUpgradeController.py:349
msgid "Sandbox setup failed"
msgstr "Установка безопасного окружения не удалась"

#: ../DistUpgrade/DistUpgradeController.py:350
msgid "It was not possible to create the sandbox environment."
msgstr "Не удалось создать безопасное окружение."

#: ../DistUpgrade/DistUpgradeController.py:356
msgid "Sandbox mode"
msgstr "Режим безопасного окружения («песочницы»)"

#: ../DistUpgrade/DistUpgradeController.py:357
#, python-format
msgid ""
"This upgrade is running in sandbox (test) mode. All changes are written to "
"'%s' and will be lost on the next reboot.\n"
"\n"
"*No* changes written to a systemdir from now until the next reboot are "
"permanent."
msgstr ""
"Обновление происходит в безопасном (тестовом) режиме. Все изменения "
"записываются в «%s» и будут стёрты после перезагрузки.\n"
"\n"
"*НИКАКИЕ* изменения системных каталогов с настоящего времени и до следующей "
"перезагрузки *НЕ* являются постоянными."

#: ../DistUpgrade/DistUpgradeController.py:385
msgid ""
"Your python install is corrupted. Please fix the '/usr/bin/python' symlink."
msgstr ""
"Python установлен некорректно. Пожалуйста, исправьте символическую ссылку "
"'/usr/bin/python'."

#: ../DistUpgrade/DistUpgradeController.py:411
msgid "Package 'debsig-verify' is installed"
msgstr "Установлен пакет «debsig-verify»"

#: ../DistUpgrade/DistUpgradeController.py:412
msgid ""
"The upgrade can not continue with that package installed.\n"
"Please remove it with synaptic or 'apt-get remove debsig-verify' first and "
"run the upgrade again."
msgstr ""
"Обновление не может быть продолжено, если установлен этот пакет.\n"
"Сначала удалите его в Synaptic или с помощью 'apt-get remove debsig-verify' "
"и запустите обновление снова."

#: ../DistUpgrade/DistUpgradeController.py:422
msgid "Include latest updates from the Internet?"
msgstr "Загрузить последние обновления из Интернета?"

#: ../DistUpgrade/DistUpgradeController.py:423
msgid ""
"The upgrade system can use the internet to automatically download the latest "
"updates and install them during the upgrade.  If you have a network "
"connection this is highly recommended.\n"
"\n"
"The upgrade will take longer, but when it is complete, your system will be "
"fully up to date.  You can choose not to do this, but you should install the "
"latest updates soon after upgrading.\n"
"If you answer 'no' here, the network is not used at all."
msgstr ""
"Последние обновления могут быть скачаны из Интернета и установлены при "
"обновлении всей системы. Если вы подключены к Интернету сделать это строго "
"рекомендуется.\n"
"\n"
"Обновление системы это долгий процесс, но по завершению, ваша система будет "
"в актуальном состоянии. Вы можете этого не делать, но рекомендуем установить "
"последние обновления как можно скорее.\n"
"Если вы ответите 'Нет', то обновления через Интернет скачаны не будут."

#: ../DistUpgrade/DistUpgradeController.py:639
#, python-format
msgid "disabled on upgrade to %s"
msgstr "заблокировано при обновлении до %s"

#: ../DistUpgrade/DistUpgradeController.py:666
msgid "No valid mirror found"
msgstr "Не найдено ни одного действующего зеркала"

#: ../DistUpgrade/DistUpgradeController.py:667
#, python-format
msgid ""
"While scanning your repository information no mirror entry for the upgrade "
"was found. This can happen if you run a internal mirror or if the mirror "
"information is out of date.\n"
"\n"
"Do you want to rewrite your 'sources.list' file anyway? If you choose 'Yes' "
"here it will update all '%s' to '%s' entries.\n"
"If you select 'No' the upgrade will cancel."
msgstr ""
"В процессе сканирования информации о Ваших репозиториях, не было найдено "
"зеркало для обновления дистрибутива. Такое возможно в случае, если Вы "
"используете внутреннее зеркало или информация о зеркалах устарела.\n"
"\n"
"Желаете ли Вы перезаписать файл 'sources.list'? Если Вы выберите 'Да', то "
"будут обновлены все '%s' записей до '%s'.\n"
"Если же Вы выберите 'Нет', то обновление будет отменено."

#. hm, still nothing useful ...
#: ../DistUpgrade/DistUpgradeController.py:687
msgid "Generate default sources?"
msgstr "Сгенерировать источники по умолчанию?"

#: ../DistUpgrade/DistUpgradeController.py:688
#, python-format
msgid ""
"After scanning your 'sources.list' no valid entry for '%s' was found.\n"
"\n"
"Should default entries for '%s' be added? If you select 'No', the upgrade "
"will cancel."
msgstr ""
"Не найдена запись для '%s' в файле 'sources.list'.\n"
"\n"
"Добавить стандартную запись для '%s'? Выбор 'Нет' означает отказ от "
"обновления."

#: ../DistUpgrade/DistUpgradeController.py:723
msgid "Repository information invalid"
msgstr "Информация о репозитории неверна"

#: ../DistUpgrade/DistUpgradeController.py:724
msgid ""
"Upgrading the repository information resulted in a invalid file. Please "
"report this as a bug."
msgstr ""
"В результате обновления информации о репозиториях образовался неверный файл. "
"Пожалуйста, отправьте отчёт об ошибке."

#: ../DistUpgrade/DistUpgradeController.py:730
msgid "Third party sources disabled"
msgstr "Источники третьих сторон отключены"

#: ../DistUpgrade/DistUpgradeController.py:731
msgid ""
"Some third party entries in your sources.list were disabled. You can re-"
"enable them after the upgrade with the 'software-properties' tool or your "
"package manager."
msgstr ""
"Некоторые источники в файле 'sources.list' были отключены. Вы сможете их "
"снова включить после обновления с помощью утилиты «Источники приложений» или "
"вашего менеджера пакетов."

#: ../DistUpgrade/DistUpgradeController.py:771
msgid "Package in inconsistent state"
msgid_plural "Packages in inconsistent state"
msgstr[0] "Пакет в неустойчивом состоянии"
msgstr[1] "Пакеты в неустойчивом состоянии"
msgstr[2] "Пакеты в неустойчивом состоянии"

#: ../DistUpgrade/DistUpgradeController.py:774
#, python-format
msgid ""
"The package '%s' is in an inconsistent state and needs to be reinstalled, "
"but no archive can be found for it. Please reinstall the package manually or "
"remove it from the system."
msgid_plural ""
"The packages '%s' are in an inconsistent state and need to be reinstalled, "
"but no archive can be found for them. Please reinstall the packages manually "
"or remove them from the system."
msgstr[0] ""
"Пакет '%s' является несовместимым и должен быть переустановлен, однако для "
"него не найден архивный файл. Переустановите пакет вручную, либо удалите его "
"из системы."
msgstr[1] ""
"Пакеты '%s' являются несовместимыми и должны быть переустановлены, однако "
"для них не найдены архивные файлы. Переустановите пакеты вручную, либо "
"удалите их из системы."
msgstr[2] ""
"Пакеты '%s' являются несовместимыми и должны быть переустановлены, однако "
"для них не найдены архивные файлы. Переустановите пакеты вручную, либо "
"удалите их из системы."

#: ../DistUpgrade/DistUpgradeController.py:822
msgid "Error during update"
msgstr "Ошибка при обновлении"

#: ../DistUpgrade/DistUpgradeController.py:823
msgid ""
"A problem occurred during the update. This is usually some sort of network "
"problem, please check your network connection and retry."
msgstr ""
"При обновлении возникла проблема. Обычно это бывает вызвано проблемами в "
"сети. Проверьте сетевые подключения и повторите попытку."

#. print "on_button_install_clicked"
#: ../DistUpgrade/DistUpgradeController.py:832
#: ../UpdateManager/UpdateManager.py:628
msgid "Not enough free disk space"
msgstr "Недостаточно свободного места на диске"

#: ../DistUpgrade/DistUpgradeController.py:833
#, python-format
msgid ""
"The upgrade has aborted. The upgrade needs a total of %s free space on disk "
"'%s'. Please free at least an additional %s of disk space on '%s'. Empty "
"your trash and remove temporary packages of former installations using 'sudo "
"apt-get clean'."
msgstr ""
"Обновление было отменено. Обновлению необходимо всего %s свободного места на "
"диске '%s'. Пожалуйста освободите как минимум дополнительно %s места на "
"'%s'. Очистите корзины и удалите временные пакеты предыдущих установок, "
"используя 'sudo apt-get clean'."

#. calc the dist-upgrade and see if the removals are ok/expected
#. do the dist-upgrade
#: ../DistUpgrade/DistUpgradeController.py:861
#: ../DistUpgrade/DistUpgradeController.py:1577
msgid "Calculating the changes"
msgstr "Вычисление изменений"

#. ask the user
#: ../DistUpgrade/DistUpgradeController.py:893
msgid "Do you want to start the upgrade?"
msgstr "Вы хотите начать обновление системы?"

#: ../DistUpgrade/DistUpgradeController.py:959
msgid "Upgrade canceled"
msgstr "Обновление отменено"

#: ../DistUpgrade/DistUpgradeController.py:960
msgid ""
"The upgrade cancels now and the original system state is restored. You can "
"resume the upgrade at a later time."
msgstr ""
"Обновление отменено. Восстановлена исходная система. Можно произвести "
"обновление позже."

#: ../DistUpgrade/DistUpgradeController.py:965
#: ../DistUpgrade/DistUpgradeController.py:1064
msgid "Could not download the upgrades"
msgstr "Не удалось загрузить обновления"

#: ../DistUpgrade/DistUpgradeController.py:966
msgid ""
"The upgrade has aborted. Please check your Internet connection or "
"installation media and try again. All files downloaded so far are kept."
msgstr ""
"Обновление было отменено. Проверьте ваше соединение с интернетом или ваш "
"установочный носитель и попробуйте снова. Все загруженые файлы будут "
"сохранены."

#. FIXME: strings are not good, but we are in string freeze
#. currently
#: ../DistUpgrade/DistUpgradeController.py:1016
#: ../DistUpgrade/DistUpgradeController.py:1052
#: ../DistUpgrade/DistUpgradeController.py:1157
msgid "Error during commit"
msgstr "Ошибка при фиксировании"

#. generate a new cache
#: ../DistUpgrade/DistUpgradeController.py:1018
#: ../DistUpgrade/DistUpgradeController.py:1054
#: ../DistUpgrade/DistUpgradeController.py:1196
msgid "Restoring original system state"
msgstr "Восстановление первоначального состояния системы"

#: ../DistUpgrade/DistUpgradeController.py:1019
#: ../DistUpgrade/DistUpgradeController.py:1033
#: ../DistUpgrade/DistUpgradeController.py:1055
msgid "Could not install the upgrades"
msgstr "Не удалось установить обновления"

#. invoke the frontend now and show a error message
#: ../DistUpgrade/DistUpgradeController.py:1024
msgid ""
"The upgrade has aborted. Your system could be in an unusable state. A "
"recovery will run now (dpkg --configure -a)."
msgstr ""
"Обновление было отменено. Ваша система может оказаться в непригодном для "
"использования состоянии. Сейчас будет запущен процесс восстановления (dpkg --"
"configure -a)."

#: ../DistUpgrade/DistUpgradeController.py:1029
#, python-format
msgid ""
"\n"
"\n"
"Please report this bug against the 'update-manager' package and include the "
"files in /var/log/dist-upgrade/ in the bug report.\n"
"%s"
msgstr ""
"\n"
"\n"
"Пожалуйста, сообщите о данной ошибке пакета 'update-manager' и включите "
"файлы из директории /var/log/dist-upgrade/ в сообщение об ошибке.\n"
"%s"

#: ../DistUpgrade/DistUpgradeController.py:1065
msgid ""
"The upgrade has aborted. Please check your Internet connection or "
"installation media and try again. "
msgstr ""
"Обновление было отменено. Проверьте Ваше соединение с интернетом или Ваш "
"установочный носитель и попробуйте снова. "

#: ../DistUpgrade/DistUpgradeController.py:1145
msgid "Remove obsolete packages?"
msgstr "Удалить устаревшие пакеты?"

#: ../DistUpgrade/DistUpgradeController.py:1146
#: ../DistUpgrade/DistUpgrade.ui.h:22
msgid "_Keep"
msgstr "_Оставить"

#: ../DistUpgrade/DistUpgradeController.py:1146
msgid "_Remove"
msgstr "_Удалить"

#: ../DistUpgrade/DistUpgradeController.py:1158
msgid ""
"A problem occurred during the clean-up. Please see the below message for "
"more information. "
msgstr ""
"Во время очистки возникла проблема. Подробности описаны в сообщении ниже. "

#. FIXME: instead of error out, fetch and install it
#. here
#: ../DistUpgrade/DistUpgradeController.py:1234
msgid "Required depends is not installed"
msgstr "Не установлены требуемые зависимости"

#: ../DistUpgrade/DistUpgradeController.py:1235
#, python-format
msgid "The required dependency '%s' is not installed. "
msgstr "Требуемая зависимость '%s' не установлена. "

#. sanity check (check for ubuntu-desktop, brokenCache etc)
#. then open the cache (again)
#: ../DistUpgrade/DistUpgradeController.py:1480
#: ../DistUpgrade/DistUpgradeController.py:1547
msgid "Checking package manager"
msgstr "Проверка менеджера пакетов"

#: ../DistUpgrade/DistUpgradeController.py:1485
msgid "Preparing the upgrade failed"
msgstr "Подготовка к обновлению завершилась неудачно"

#: ../DistUpgrade/DistUpgradeController.py:1486
msgid ""
"Preparing the system for the upgrade failed. Please report this as a bug "
"against the 'update-manager' package and include the files in /var/log/dist-"
"upgrade/ in the bug report."
msgstr ""
"Подготовка системы к обновлению не удалась. Сообщите, пожалуйста, об ошибке, "
"связанной с пакетом \"update-manager\", и приложите файлы из /var/log/dist-"
"upgrade/ к сообщению."

#: ../DistUpgrade/DistUpgradeController.py:1502
msgid "Getting upgrade prerequisites failed"
msgstr "Подготовка к обновлению завершилась неудачно"

#: ../DistUpgrade/DistUpgradeController.py:1503
msgid ""
"The system was unable to get the prerequisites for the upgrade. The upgrade "
"will abort now and restore the original system state.\n"
"\n"
"Please report this as a bug against the 'update-manager' package and include "
"the files in /var/log/dist-upgrade/ in the bug report."
msgstr ""
"Системе не удалось получить необходимые условия обновления. Обновление будет "
"прервано и система вернётся в первоначальное состояние.\n"
"Пожалуйста, сообщите об этой ошибке, приложив к отчёту файлы из "
"/var/log/dist-upgrade/."

#: ../DistUpgrade/DistUpgradeController.py:1533
msgid "Updating repository information"
msgstr "Обновление информации о репозитории"

#: ../DistUpgrade/DistUpgradeController.py:1565
msgid "Invalid package information"
msgstr "Неверная информация о пакете"

#: ../DistUpgrade/DistUpgradeController.py:1566
#, python-format
msgid ""
"After your package information was updated the essential package '%s' can "
"not be found anymore.\n"
"This indicates a serious error, please report this bug against the 'update-"
"manager' package and include the files in /var/log/dist-upgrade/ in the bug "
"report."
msgstr ""
"После обновления информации о пакетах нельзя больше найти необходимый пакет "
"\"%s\".\n"
"Это является серьёзной ошибкой. Сообщите, пожалуйста, об этой ошибке, "
"связанной с пакетом \"update-manager\", и приложите файлы из /var/log/dist-"
"upgrade/ к сообщению."

#: ../DistUpgrade/DistUpgradeController.py:1583
#: ../DistUpgrade/DistUpgradeController.py:1631
msgid "Fetching"
msgstr "Загрузка"

#: ../DistUpgrade/DistUpgradeController.py:1589
#: ../DistUpgrade/DistUpgradeController.py:1635
msgid "Upgrading"
msgstr "Обновление"

#. don't abort here, because it would restore the sources.list
#: ../DistUpgrade/DistUpgradeController.py:1594
#: ../DistUpgrade/DistUpgradeController.py:1637
#: ../DistUpgrade/DistUpgradeController.py:1644
#: ../DistUpgrade/DistUpgradeController.py:1655
msgid "Upgrade complete"
msgstr "Обновление завершено"

#: ../DistUpgrade/DistUpgradeController.py:1595
#: ../DistUpgrade/DistUpgradeController.py:1638
#: ../DistUpgrade/DistUpgradeController.py:1645
msgid ""
"The upgrade is completed but there were errors during the upgrade process."
msgstr "Обновление завершено, но во время обновления произошли ошибки."

#: ../DistUpgrade/DistUpgradeController.py:1602
msgid "Searching for obsolete software"
msgstr "Поиск устаревших программ"

#: ../DistUpgrade/DistUpgradeController.py:1607
msgid "System upgrade is complete."
msgstr "Обновление системы завершено."

#: ../DistUpgrade/DistUpgradeController.py:1656
msgid "The partial upgrade was completed."
msgstr "Частичное обновление завершено."

#: ../DistUpgrade/DistUpgradeQuirks.py:168
msgid "evms in use"
msgstr "Программа 'evms' используется"

#: ../DistUpgrade/DistUpgradeQuirks.py:169
msgid ""
"Your system uses the 'evms' volume manager in /proc/mounts. The 'evms' "
"software is no longer supported, please switch it off and run the upgrade "
"again when this is done."
msgstr ""
"Ваша система использует медежер томов 'evms' в /proc/mounts. Программа "
"'evms' больше не поддерживается. Пожалуйста, закройте её и запустите "
"обновление снова."

#: ../DistUpgrade/DistUpgradeQuirks.py:434
#: ../DistUpgrade/DistUpgradeQuirks.py:462
#: ../DistUpgrade/DistUpgradeQuirks.py:489
msgid ""
"Upgrading may reduce desktop effects, and performance in games and other "
"graphically intensive programs."
msgstr ""
"Обновление может повлечь снижение качества эффектов рабочего стола и "
"производительности в играх и приложениях, активно работающих с графикой."

#: ../DistUpgrade/DistUpgradeQuirks.py:438
#: ../DistUpgrade/DistUpgradeQuirks.py:466
msgid ""
"This computer is currently using the NVIDIA 'nvidia' graphics driver. No "
"version of this driver is available that works with your video card in "
"Ubuntu 10.04 LTS.\n"
"\n"
"Do you want to continue?"
msgstr ""
"На этом компьютере используются драйвера NVIDIA. Нет доступных версий этих "
"драйверов, которые бы работали с вашей видеокартой в Ubuntu 10.04 LTS.\n"
"\n"
"Вы хотите продолжить?"

#: ../DistUpgrade/DistUpgradeQuirks.py:493
msgid ""
"This computer is currently using the AMD 'fglrx' graphics driver. No version "
"of this driver is available that works with your hardware in Ubuntu 10.04 "
"LTS.\n"
"\n"
"Do you want to continue?"
msgstr ""
"На этом компьютере используются драйвера AMD 'fglrx'.  Нет доступных версий "
"этих драйверов, которые бы работали с вашим оборудованием в Ubuntu 10.04 "
"LTS.\n"
"\n"
"Вы хотите продолжить?"

#: ../DistUpgrade/DistUpgradeQuirks.py:520
msgid "No ARMv6 CPU"
msgstr "Нет процессора ARMv6"

#: ../DistUpgrade/DistUpgradeQuirks.py:521
msgid ""
"Your system uses an ARM CPU that is older than the ARMv6 architecture. All "
"packages in karmic were built with optimizations requiring ARMv6 as the "
"minimal architecture. It is not possible to upgrade your system to a new "
"Ubuntu release with this hardware."
msgstr ""
"Ваша система использует процессор архитектуры ARM, старше архитектуры ARMv6. "
"Все пакеты в karmic были построены с оптимизацией под архитектуру ARMv6 и "
"выше. Вашу систему невозможно обновить до нового релиза Ubuntu с текущим "
"аппаратным обеспечением."

#: ../DistUpgrade/DistUpgradeQuirks.py:541
msgid "No init available"
msgstr "Служба init недоступна"

#: ../DistUpgrade/DistUpgradeQuirks.py:542
msgid ""
"Your system appears to be a virtualised environment without an init daemon, "
"e.g. Linux-VServer. Ubuntu 10.04 LTS cannot function within this type of "
"environment, requiring an update to your virtual machine configuration "
"first.\n"
"\n"
"Are you sure you want to continue?"
msgstr ""
"Похоже, что ваша система является виртуализованным окружением без службы "
"init, например Linux-VServer. Ubuntu 10.04 LTS не может работать в таком "
"типе окружения, вы должны вначале исправить конфигурацию своей виртуальной "
"машины.\n"
"\n"
"Вы уверены, что хотите продолжить?"

#: ../DistUpgrade/DistUpgradeMain.py:47
msgid "Sandbox upgrade using aufs"
msgstr "Обновление в безопасном окружении, используя aufs"

#: ../DistUpgrade/DistUpgradeMain.py:49
msgid "Use the given path to search for a cdrom with upgradable packages"
msgstr ""
"Использовать данный путь для поиска компакт-диска с пакетами обновлений"

#: ../DistUpgrade/DistUpgradeMain.py:55
msgid ""
"Use frontend. Currently available: \n"
"DistUpgradeViewText, DistUpgradeViewGtk, DistUpgradeViewKDE"
msgstr ""
"Использовать интерфейс. Сейчас доступны: \n"
"DistUpgradeViewText, DistUpgradeViewGtk, DistUpgradeViewKDE"

#: ../DistUpgrade/DistUpgradeMain.py:58
msgid "*DEPRECATED* this option will be ignore"
msgstr "*НЕ РЕКОММЕНДУЕТСЯ* эта опция будет проигнорирована"

#: ../DistUpgrade/DistUpgradeMain.py:61
msgid "Perform a partial upgrade only (no sources.list rewriting)"
msgstr ""
"Подготовить только частичное обновление (sources.list перезаписан не будет)"

#: ../DistUpgrade/DistUpgradeMain.py:63
msgid "Set datadir"
msgstr "Установить каталог с данными"

#. print "mediaChange %s %s" % (medium, drive)
#: ../DistUpgrade/DistUpgradeViewGtk.py:113
#: ../DistUpgrade/DistUpgradeViewKDE.py:190
#: ../UpdateManager/DistUpgradeFetcherKDE.py:148
#, python-format
msgid "Please insert '%s' into the drive '%s'"
msgstr "Пожалуйста, вставьте '%s' в устройство '%s'"

#: ../DistUpgrade/DistUpgradeViewGtk.py:134
#: ../DistUpgrade/DistUpgradeViewKDE.py:204
msgid "Fetching is complete"
msgstr "Загрузка завершена"

#: ../DistUpgrade/DistUpgradeViewGtk.py:145
#: ../DistUpgrade/DistUpgradeViewKDE.py:217
#, python-format
msgid "Fetching file %li of %li at %sB/s"
msgstr "Загрузка файла %li из %li на скорости %s Байт/сек"

#: ../DistUpgrade/DistUpgradeViewGtk.py:148
#: ../DistUpgrade/DistUpgradeViewGtk.py:288
#: ../DistUpgrade/DistUpgradeViewKDE.py:218
#: ../DistUpgrade/DistUpgradeViewKDE.py:358
#, python-format
msgid "About %s remaining"
msgstr "Осталось приблизительно %s"

#: ../DistUpgrade/DistUpgradeViewGtk.py:151
#: ../DistUpgrade/DistUpgradeViewKDE.py:220
#, python-format
msgid "Fetching file %li of %li"
msgstr "Загрузка файла %li из %li"

#. FIXME: add support for the timeout
#. of the terminal (to display something useful then)
#. -> longer term, move this code into python-apt
#: ../DistUpgrade/DistUpgradeViewGtk.py:183
#: ../DistUpgrade/DistUpgradeViewKDE.py:254
msgid "Applying changes"
msgstr "Применение изменений"

#. we do not report followup errors from earlier failures
#: ../DistUpgrade/DistUpgradeViewGtk.py:208
#: ../DistUpgrade/DistUpgradeViewKDE.py:267
msgid "dependency problems - leaving unconfigured"
msgstr "проблемы зависимостей — оставляем не настроенным"

#: ../DistUpgrade/DistUpgradeViewGtk.py:213
#: ../DistUpgrade/DistUpgradeViewKDE.py:269
#, python-format
msgid "Could not install '%s'"
msgstr "Не удалось установить «%s»"

#: ../DistUpgrade/DistUpgradeViewGtk.py:214
#: ../DistUpgrade/DistUpgradeViewKDE.py:270
#, python-format
msgid ""
"The upgrade will continue but the '%s' package may not be in a working "
"state. Please consider submitting a bug report about it."
msgstr ""
"Обновление будет продолжено, но  '%s' пакета(ов) могут быть в нерабочем "
"состоянии. Просьба рассмотреть вопрос о представлении отчета об этой ошибке."

#. self.expander.set_expanded(True)
#: ../DistUpgrade/DistUpgradeViewGtk.py:231
#: ../DistUpgrade/DistUpgradeViewKDE.py:291
#, python-format
msgid ""
"Replace the customized configuration file\n"
"'%s'?"
msgstr ""
"Заменить изменённый конфигурационный файл\n"
"'%s'?"

#: ../DistUpgrade/DistUpgradeViewGtk.py:232
#: ../DistUpgrade/DistUpgradeViewKDE.py:292
msgid ""
"You will lose any changes you have made to this configuration file if you "
"choose to replace it with a newer version."
msgstr ""
"Вы потеряете все изменения, которые сделали в этом файле конфигурации, если "
"замените его новой версией."

#: ../DistUpgrade/DistUpgradeViewGtk.py:246
#: ../DistUpgrade/DistUpgradeViewKDE.py:310
msgid "The 'diff' command was not found"
msgstr "Не найдена команда 'diff'"

#: ../DistUpgrade/DistUpgradeViewGtk.py:454
#: ../DistUpgrade/DistUpgradeViewText.py:88
msgid "A fatal error occurred"
msgstr "Произошла критическая ошибка"

#: ../DistUpgrade/DistUpgradeViewGtk.py:455
msgid ""
"Please report this as a bug (if you haven't already) and include the files "
"/var/log/dist-upgrade/main.log and /var/log/dist-upgrade/apt.log in your "
"report. The upgrade has aborted.\n"
"Your original sources.list was saved in /etc/apt/sources.list.distUpgrade."
msgstr ""
"Пожалуйста, сообщите об этом как об ошибке (если Вы ещё этого не сделали) и "
"включите файлы /var/log/dist-upgrade/main.log и /var/log/dist-"
"upgrade/apt.log в ваш отчёт. Обновление было отменено.\n"
"Ваш оригинальный файл sources.list был сохранён в "
"/etc/apt/sources.list.distUpgrade."

#: ../DistUpgrade/DistUpgradeViewGtk.py:472
msgid "Ctrl-c pressed"
msgstr "Нажаты Ctrl+c"

#: ../DistUpgrade/DistUpgradeViewGtk.py:473
msgid ""
"This will abort the operation and may leave the system in a broken state. "
"Are you sure you want to do that?"
msgstr ""
"Операция будет отменена, что может привести к нерабочему состоянию системы. "
"Вы действительно хотите продолжить?"

#. append warning
#: ../DistUpgrade/DistUpgradeViewGtk.py:621
msgid "To prevent data loss close all open applications and documents."
msgstr ""
"Чтобы избежать потерь данных, закройте все открытые приложения и документы."

#: ../DistUpgrade/DistUpgradeViewGtk.py:635
#, python-format
msgid "No longer supported by Canonical (%s)"
msgstr "Больше не поддерживается компанией Canonical (%s)"

#: ../DistUpgrade/DistUpgradeViewGtk.py:636
#, python-format
msgid "<b>Downgrade (%s)</b>"
msgstr "<b>Установка старой версии (%s)</b>"

#: ../DistUpgrade/DistUpgradeViewGtk.py:637
#, python-format
msgid "Remove (%s)"
msgstr "Удаление (%s)"

#: ../DistUpgrade/DistUpgradeViewGtk.py:638
#, python-format
msgid "No longer needed (%s)"
msgstr "Больше не нужен (%s)"

#: ../DistUpgrade/DistUpgradeViewGtk.py:639
#, python-format
msgid "Install (%s)"
msgstr "Установка (%s)"

#: ../DistUpgrade/DistUpgradeViewGtk.py:640
#, python-format
msgid "Upgrade (%s)"
msgstr "Обновление (%s)"

#. change = QMessageBox.question(None, _("Media Change"), msg, QMessageBox.Ok, QMessageBox.Cancel)
#: ../DistUpgrade/DistUpgradeViewKDE.py:191
#: ../UpdateManager/DistUpgradeFetcherKDE.py:150
msgid "Media Change"
msgstr "Смена носителя"

#: ../DistUpgrade/DistUpgradeViewKDE.py:322
msgid "Show Difference >>>"
msgstr "Показать различия >>>"

#: ../DistUpgrade/DistUpgradeViewKDE.py:325
msgid "<<< Hide Difference"
msgstr "<<< Скрыть различия"

#: ../DistUpgrade/DistUpgradeViewKDE.py:539
msgid "Error"
msgstr "Ошибка"

#: ../DistUpgrade/DistUpgradeViewKDE.py:551
msgid "&Cancel"
msgstr "О&тмена"

#: ../DistUpgrade/DistUpgradeViewKDE.py:553
#: ../DistUpgrade/DistUpgradeViewKDE.py:795
msgid "&Close"
msgstr "&Закрыть"

#: ../DistUpgrade/DistUpgradeViewKDE.py:599
msgid "Show Terminal >>>"
msgstr "Показать терминал >>>"

#: ../DistUpgrade/DistUpgradeViewKDE.py:602
msgid "<<< Hide Terminal"
msgstr "<<< Скрыть терминал"

#: ../DistUpgrade/DistUpgradeViewKDE.py:682
msgid "Information"
msgstr "Сведения"

#: ../DistUpgrade/DistUpgradeViewKDE.py:733
#: ../DistUpgrade/DistUpgradeViewKDE.py:778
#: ../DistUpgrade/DistUpgradeViewKDE.py:781 ../DistUpgrade/DistUpgrade.ui.h:11
msgid "Details"
msgstr "Подробности"

#: ../DistUpgrade/DistUpgradeViewKDE.py:759
#, python-format
msgid "No longer supported %s"
msgstr "Больше не поддерживается (%s)"

#: ../DistUpgrade/DistUpgradeViewKDE.py:761
#, python-format
msgid "Remove %s"
msgstr "Удалить %s"

#: ../DistUpgrade/DistUpgradeViewKDE.py:763
#: ../DistUpgrade/DistUpgradeViewText.py:175
#, python-format
msgid "Remove (was auto installed) %s"
msgstr "Удалить %s (было установлено автоматически)"

#: ../DistUpgrade/DistUpgradeViewKDE.py:765
#, python-format
msgid "Install %s"
msgstr "Установить %s"

#: ../DistUpgrade/DistUpgradeViewKDE.py:767
#, python-format
msgid "Upgrade %s"
msgstr "Обновить %s"

#: ../DistUpgrade/DistUpgradeViewKDE.py:791
#: ../DistUpgrade/DistUpgradeViewText.py:223
msgid "Restart required"
msgstr "Требуется перезагрузка"

#: ../DistUpgrade/DistUpgradeViewKDE.py:791
msgid "<b><big>Restart the system to complete the upgrade</big></b>"
msgstr "<b><big>Для завершения обновления перезагрузите систему</big></b>"

#: ../DistUpgrade/DistUpgradeViewKDE.py:794 ../DistUpgrade/DistUpgrade.ui.h:25
#: ../data/glade/UpdateManager.ui.h:31
msgid "_Restart Now"
msgstr "_Перезагрузить сейчас"

#. FIXME make this user friendly
#: ../DistUpgrade/DistUpgradeViewKDE.py:812
msgid ""
"<b><big>Cancel the running upgrade?</big></b>\n"
"\n"
"The system could be in an unusable state if you cancel the upgrade. You are "
"strongly advised to resume the upgrade."
msgstr ""
"<b><big>Прервать обновление?</big></b>\n"
"Если вы прервёте обновление, система может работать нестабильно. "
"Настоятельно рекомендуем продолжить обновление."

#: ../DistUpgrade/DistUpgradeViewKDE.py:816
msgid "Cancel Upgrade?"
msgstr "Отменить обновление?"

#: ../DistUpgrade/DistUpgradeView.py:60
#, python-format
msgid "%li day"
msgid_plural "%li days"
msgstr[0] "%li день"
msgstr[1] "%li дня"
msgstr[2] "%li дней"

#: ../DistUpgrade/DistUpgradeView.py:62
#, python-format
msgid "%li hour"
msgid_plural "%li hours"
msgstr[0] "%li час"
msgstr[1] "%li часа"
msgstr[2] "%li часов"

#: ../DistUpgrade/DistUpgradeView.py:64
#, python-format
msgid "%li minute"
msgid_plural "%li minutes"
msgstr[0] "%li минута"
msgstr[1] "%li минуты"
msgstr[2] "%li минут"

#: ../DistUpgrade/DistUpgradeView.py:65
#, python-format
msgid "%li second"
msgid_plural "%li seconds"
msgstr[0] "%li секунда"
msgstr[1] "%li секунды"
msgstr[2] "%li секунд"

#. TRANSLATORS: you can alter the ordering of the remaining time
#. information here if you shuffle %(str_days)s %(str_hours)s %(str_minutes)s
#. around. Make sure to keep all '$(str_*)s' in the translated string
#. and do NOT change anything appart from the ordering.
#. 
#. %(str_hours)s will be either "1 hour" or "2 hours" depending on the
#. plural form
#. 
#. Note: most western languages will not need to change this
#: ../DistUpgrade/DistUpgradeView.py:81
#, python-format
msgid "%(str_days)s %(str_hours)s"
msgstr "%(str_days)s %(str_hours)s"

#. TRANSLATORS: you can alter the ordering of the remaining time
#. information here if you shuffle %(str_hours)s %(str_minutes)s
#. around. Make sure to keep all '$(str_*)s' in the translated string
#. and do NOT change anything appart from the ordering.
#. 
#. %(str_hours)s will be either "1 hour" or "2 hours" depending on the
#. plural form
#. 
#. Note: most western languages will not need to change this
#: ../DistUpgrade/DistUpgradeView.py:99
#, python-format
msgid "%(str_hours)s %(str_minutes)s"
msgstr "%(str_hours)s %(str_minutes)s"

#. 56 kbit
#. 1Mbit = 1024 kbit
#: ../DistUpgrade/DistUpgradeView.py:147
#, python-format
msgid ""
"This download will take about %s with a 1Mbit DSL connection and about %s "
"with a 56k modem."
msgstr ""
"Загрузка займёт около %s при 1Мбит DSL соединении и около %s при модемном "
"соединении на скорости 56Кбит."

#. if we have a estimated speed, use it
#: ../DistUpgrade/DistUpgradeView.py:151
#, python-format
msgid "This download will take about %s with your connection. "
msgstr "Загрузка займёт примерно %s на вашем соединении. "

#: ../DistUpgrade/DistUpgradeView.py:253 ../DistUpgrade/DistUpgrade.ui.h:16
msgid "Preparing to upgrade"
msgstr "Подготовка к обновлению"

#: ../DistUpgrade/DistUpgradeView.py:254
msgid "Getting new software channels"
msgstr "Изменение источников приложений"

#: ../DistUpgrade/DistUpgradeView.py:255 ../DistUpgrade/DistUpgrade.ui.h:14
msgid "Getting new packages"
msgstr "Загрузка новых пакетов"

#: ../DistUpgrade/DistUpgradeView.py:256 ../DistUpgrade/DistUpgrade.ui.h:15
msgid "Installing the upgrades"
msgstr "Установка обновлений"

#: ../DistUpgrade/DistUpgradeView.py:257 ../DistUpgrade/DistUpgrade.ui.h:10
msgid "Cleaning up"
msgstr "Очистка"

#: ../DistUpgrade/DistUpgradeView.py:341
#, python-format
msgid ""
"%(amount)d installed package is no longer supported by Canonical. You can "
"still get support from the community."
msgid_plural ""
"%(amount)d installed packages are no longer supported by Canonical. You can "
"still get support from the community."
msgstr[0] ""
"%(amount)d установленный пакет больше не поддерживаются Canonical. Вы можете "
"получить поддержку у сообщества."
msgstr[1] ""
"%(amount)d установленных пакетов больше не поддерживаются Canonical. Вы "
"можете получить поддержку у сообщества."
msgstr[2] ""
"%(amount)d установленных пакетов больше не поддерживаются Canonical. Вы "
"можете получить поддержку у сообщества."

#. FIXME: make those two separate lines to make it clear
#. that the "%" applies to the result of ngettext
#: ../DistUpgrade/DistUpgradeView.py:350
#, python-format
msgid "%d package is going to be removed."
msgid_plural "%d packages are going to be removed."
msgstr[0] "%d пакет будет удалён."
msgstr[1] "%d пакета будут удалены."
msgstr[2] "%d пакетов будут удалены."

#: ../DistUpgrade/DistUpgradeView.py:355
#, python-format
msgid "%d new package is going to be installed."
msgid_plural "%d new packages are going to be installed."
msgstr[0] "%d новый пакет будет установлен."
msgstr[1] "%d новых пакета будут установлены."
msgstr[2] "%d новых пакетов будут установлены."

#: ../DistUpgrade/DistUpgradeView.py:361
#, python-format
msgid "%d package is going to be upgraded."
msgid_plural "%d packages are going to be upgraded."
msgstr[0] "%d пакет будет обновлён."
msgstr[1] "%d пакета будут обновлены."
msgstr[2] "%d пакетов будут обновлены."

#: ../DistUpgrade/DistUpgradeView.py:366
#, python-format
msgid ""
"\n"
"\n"
"You have to download a total of %s. "
msgstr ""
"\n"
"\n"
"Всего требуется загрузить %s. "

#: ../DistUpgrade/DistUpgradeView.py:370
msgid ""
"Fetching and installing the upgrade can take several hours. Once the "
"download has finished, the process cannot be cancelled."
msgstr ""
"Загрузка и установка обновлений может занять несколько часов. После "
"завершения загрузки этот процесс не может быть отменён."

#. FIXME: this should go into DistUpgradeController
#: ../DistUpgrade/DistUpgradeView.py:376 ../UpdateManager/UpdateManager.py:557
msgid "Your system is up-to-date"
msgstr "Ваша система не требует обновления"

#: ../DistUpgrade/DistUpgradeView.py:377
msgid ""
"There are no upgrades available for your system. The upgrade will now be "
"canceled."
msgstr ""
"Для вашей системы не доступно ни одно обновление. Обновление будет отменено."

#: ../DistUpgrade/DistUpgradeView.py:390
msgid "Reboot required"
msgstr "Требуется перезагрузка"

#: ../DistUpgrade/DistUpgradeView.py:391
msgid ""
"The upgrade is finished and a reboot is required. Do you want to do this now?"
msgstr ""
"Обновление завершено и требуется перезагрузка. Перезагрузиться сейчас?"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:135
#: ../DistUpgrade/DistUpgradeFetcherCore.py:136
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:135
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:136
msgid "Could not run the upgrade tool"
msgstr "Не удалось запустить утилиту обновления"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:136
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:136
msgid ""
"This is most likely a bug in the upgrade tool. Please report it as a bug"
msgstr ""
"Скорее всего, это вызвано ошибкой в утилите обновления. Пожалуйста, сообщите "
"об ошибке."

#: ../DistUpgrade/DistUpgradeFetcherCore.py:205
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:205
msgid "Upgrade tool signature"
msgstr "Подпись утилиты обновления"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:208
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:208
msgid "Upgrade tool"
msgstr "Утилита обновления"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:237
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:237
msgid "Failed to fetch"
msgstr "Не удалось получить"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:238
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:238
msgid "Fetching the upgrade failed. There may be a network problem. "
msgstr "Не удалось получить обновление. Возможно, возникла проблема в сети. "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:242
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:242
msgid "Failed to extract"
msgstr "Не удалось извлечь"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:243
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:243
msgid ""
"Extracting the upgrade failed. There may be a problem with the network or "
"with the server. "
msgstr ""
"Не удалось извлечь обновление. Возможно, возникла проблема в сети или на "
"сервере. "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:248
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:248
msgid "Verification failed"
msgstr "Проверка не удалась"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:249
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:249
msgid ""
"Verifying the upgrade failed.  There may be a problem with the network or "
"with the server. "
msgstr ""
"Проверка обновления завершилась неудачно. Возможно, возникла проблема в сети "
"или на сервере. "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:254
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:254
msgid "Authentication failed"
msgstr "Проверка подлинности не удалась"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:255
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:255
msgid ""
"Authenticating the upgrade failed. There may be a problem with the network "
"or with the server. "
msgstr ""
"Проверка подлинности обновления завершилась неудачно. Возможно, возникла "
"проблема в сети или на сервере. "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:269
#: ../DistUpgrade/DistUpgradeFetcherCore.py:275
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:269
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:275
msgid "Can not run the upgrade"
msgstr "Невозможно запустить процесс обновления"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:270
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:270
msgid ""
"This usually is caused by a system were /tmp is mounted noexec. Please "
"remount without noexec and run the upgrade again."
msgstr ""
"Это обычно происходит, если /tmp смонтирован с опцией noexec. Пожалуйста, "
"перемонтируйте каталог без этой опции и запустите обновление снова."

#: ../DistUpgrade/DistUpgradeFetcherCore.py:276
#: ../UpdateManager/Core/DistUpgradeFetcherCore.py:276
#, python-format
msgid "The error message is '%s'."
msgstr "Сообщение об ошибке '%s'."

#: ../DistUpgrade/DistUpgradeViewText.py:89
msgid ""
"Please report this as a bug and include the files /var/log/dist-"
"upgrade/main.log and /var/log/dist-upgrade/apt.log in your report. The "
"upgrade has aborted.\n"
"Your original sources.list was saved in /etc/apt/sources.list.distUpgrade."
msgstr ""
"Пожалуйста сообщите об этом как о баге и включите файлы /var/log/dist-"
"upgrade/main.log и /var/log/dist-upgrade/apt.log в ваш отчёт. Обновление "
"было отменено. Ваш оригинальный файл sources.list был сохранён в "
"/etc/apt/sources.list.distUpgrade."

#: ../DistUpgrade/DistUpgradeViewText.py:113
msgid "Aborting"
msgstr "Прерывание"

#: ../DistUpgrade/DistUpgradeViewText.py:118
msgid "Demoted:\n"
msgstr "Понижено:\n"

#: ../DistUpgrade/DistUpgradeViewText.py:151
#: ../DistUpgrade/DistUpgradeViewText.py:189
#: ../DistUpgrade/DistUpgradeViewText.py:196
msgid "Continue [yN] "
msgstr "Продолжить [дН] "

#: ../DistUpgrade/DistUpgradeViewText.py:151
#: ../DistUpgrade/DistUpgradeViewText.py:189
msgid "Details [d]"
msgstr "Подробности [п]"

#. TRANSLATORS: the "y" is "yes"
#. TRANSLATORS: first letter of a positive (yes) answer
#: ../DistUpgrade/DistUpgradeViewText.py:155
#: ../DistUpgrade/DistUpgradeViewText.py:199
msgid "y"
msgstr "д"

#. TRANSLATORS: the "n" is "no"
#. TRANSLATORS: first letter of a negative (no) answer
#: ../DistUpgrade/DistUpgradeViewText.py:158
#: ../DistUpgrade/DistUpgradeViewText.py:206
msgid "n"
msgstr "н"

#. TRANSLATORS: the "d" is "details"
#: ../DistUpgrade/DistUpgradeViewText.py:161
msgid "d"
msgstr "п"

#: ../DistUpgrade/DistUpgradeViewText.py:166
#, python-format
msgid "No longer supported: %s\n"
msgstr "Больше не поддерживается: %s\n"

#: ../DistUpgrade/DistUpgradeViewText.py:171
#, python-format
msgid "Remove: %s\n"
msgstr "Удалить: %s\n"

#: ../DistUpgrade/DistUpgradeViewText.py:181
#, python-format
msgid "Install: %s\n"
msgstr "Установить: %s\n"

#: ../DistUpgrade/DistUpgradeViewText.py:186
#, python-format
msgid "Upgrade: %s\n"
msgstr "Обновить: %s\n"

#: ../DistUpgrade/DistUpgradeViewText.py:203
msgid "Continue [Yn] "
msgstr "Продолжить [Дн] "

#: ../DistUpgrade/DistUpgradeViewText.py:224
msgid ""
"To finish the upgrade, a restart is required.\n"
"If you select 'y' the system will be restarted."
msgstr ""
"Чтобы завершить обновление, требуется перезагрузка.\n"
"Если вы выберите 'д', система будет перезагружена."

#: ../DistUpgrade/DistUpgrade.ui.h:1
msgid "    "
msgstr "    "

#: ../DistUpgrade/DistUpgrade.ui.h:2
msgid ""
"<b><big>Cancel the running upgrade?</big></b>\n"
"\n"
"The system could be in an unusable state if you cancel the upgrade. You are "
"strongly adviced to resume the upgrade."
msgstr ""
"<b><big>Прервать текущее обновление?</big></b>\n"
"\n"
"Если вы прервёте обновление, система может оказаться в неработоспособном "
"состоянии. Настоятельно рекомендуется продолжить обновление."

#: ../DistUpgrade/DistUpgrade.ui.h:5
msgid ""
"<b><big>Restart the system to complete the upgrade</big></b>\n"
"\n"
"Please save your work before continuing."
msgstr ""
"<b><big>Перезагрузите систему для завершения обновления.</big></b>\n"
"\n"
"Пожалуйста, сохраните свои документы перед продолжением."

#: ../DistUpgrade/DistUpgrade.ui.h:8
msgid "<b><big>Start the upgrade?</big></b>"
msgstr "<b><big>Начать обновление?</big></b>"

#: ../DistUpgrade/DistUpgrade.ui.h:9
msgid "<b><big>Upgrading Ubuntu to version 10.10</big></b>"
msgstr "<b><big>Обновление Ubuntu до версии 10.10</big></b>"

#: ../DistUpgrade/DistUpgrade.ui.h:12
msgid "Difference between the files"
msgstr "Различие между файлами"

#: ../DistUpgrade/DistUpgrade.ui.h:13
msgid "Distribution Upgrade"
msgstr "Обновление дистрибутива"

#: ../DistUpgrade/DistUpgrade.ui.h:17
msgid "Restarting the computer"
msgstr "Перезагрузка системы"

#: ../DistUpgrade/DistUpgrade.ui.h:18
msgid "Setting new software channels"
msgstr "Установка новых источников приложений"

#: ../DistUpgrade/DistUpgrade.ui.h:19
msgid "Terminal"
msgstr "Терминал"

#: ../DistUpgrade/DistUpgrade.ui.h:20
msgid "_Cancel Upgrade"
msgstr "_Отменить обновление"

#: ../DistUpgrade/DistUpgrade.ui.h:21
msgid "_Continue"
msgstr "_Продолжить"

#: ../DistUpgrade/DistUpgrade.ui.h:23
msgid "_Replace"
msgstr "_Заменить"

#: ../DistUpgrade/DistUpgrade.ui.h:24
msgid "_Report Bug"
msgstr "_Отправить сообщение об ошибке"

#: ../DistUpgrade/DistUpgrade.ui.h:26
msgid "_Resume Upgrade"
msgstr "_Продолжить обновление"

#: ../DistUpgrade/DistUpgrade.ui.h:27
msgid "_Start Upgrade"
msgstr "_Начать обновление"

#: ../UpdateManager/backend/InstallBackendSynaptic.py:54
msgid "Please wait, this can take some time."
msgstr "Пожалуйста, подождите, это может занять некоторое время."

#: ../UpdateManager/backend/InstallBackendSynaptic.py:56
msgid "Update is complete"
msgstr "Обновление завершено"

#: ../UpdateManager/DistUpgradeFetcher.py:85
#: ../UpdateManager/DistUpgradeFetcherKDE.py:103
msgid "Could not find the release notes"
msgstr "Не удалось найти примечания к выпуску"

#: ../UpdateManager/DistUpgradeFetcher.py:86
#: ../UpdateManager/DistUpgradeFetcherKDE.py:104
msgid "The server may be overloaded. "
msgstr "Возможно, сервер перегружен. "

#: ../UpdateManager/DistUpgradeFetcher.py:96
#: ../UpdateManager/DistUpgradeFetcherKDE.py:108
msgid "Could not download the release notes"
msgstr "Не удалось загрузить примечания к выпуску"

#: ../UpdateManager/DistUpgradeFetcher.py:97
#: ../UpdateManager/DistUpgradeFetcherKDE.py:109
msgid "Please check your internet connection."
msgstr "Пожалуйста, проверьте ваше сетевое соединение."

#: ../UpdateManager/DistUpgradeFetcherKDE.py:62
#: ../UpdateManager/DistUpgradeFetcherKDE.py:85
msgid "Upgrade"
msgstr "Обновление"

#: ../UpdateManager/DistUpgradeFetcherKDE.py:89
#: ../data/glade/UpdateManager.ui.h:13
#: ../data/glade/UpgradePromptDialog.ui.h:4
msgid "Release Notes"
msgstr "Примечания к выпуску"

#: ../UpdateManager/DistUpgradeFetcherKDE.py:128
#: ../UpdateManager/DistUpgradeFetcherKDE.py:141
#: ../UpdateManager/DistUpgradeFetcherKDE.py:143
msgid "Downloading additional package files..."
msgstr "Загрузка дополнительных файлов пакетов..."

#: ../UpdateManager/DistUpgradeFetcherKDE.py:141
#, python-format
msgid "File %s of %s at %sB/s"
msgstr "Файл %s из %s на скорости %sБ/с"

#: ../UpdateManager/DistUpgradeFetcherKDE.py:143
#, python-format
msgid "File %s of %s"
msgstr "Файл %s из %s"

#: ../UpdateManager/ChangelogViewer.py:70
msgid "Open Link in Browser"
msgstr "Открыть ссылку в браузере"

#: ../UpdateManager/ChangelogViewer.py:72
msgid "Copy Link to Clipboard"
msgstr "Копировать ссылку в буфер"

#: ../UpdateManager/GtkProgress.py:161
#, python-format
msgid "Downloading file %(current)li of %(total)li with %(speed)s/s"
msgstr "Загрузка файла %(current)li из %(total)li со скоростью %(speed)s/с"

#: ../UpdateManager/GtkProgress.py:166
#, python-format
msgid "Downloading file %(current)li of %(total)li"
msgstr "Загрузка файла %(current)li из %(total)li"

#: ../UpdateManager/UpdateManager.py:326
#, python-format
msgid "Version %s: \n"
msgstr "Версия %s: \n"

#: ../UpdateManager/UpdateManager.py:383
msgid "Downloading list of changes..."
msgstr "Загрузка списка изменений..."

#: ../UpdateManager/UpdateManager.py:423
msgid "_Uncheck All"
msgstr "_Снять все отметки"

#: ../UpdateManager/UpdateManager.py:429
msgid "_Check All"
msgstr "_Установить все отметки"

#: ../UpdateManager/UpdateManager.py:476
#, python-format
msgid "%(count)s update has been selected."
msgid_plural "%(count)s updates have been selected."
msgstr[0] "%(count)s обновление выбрано."
msgstr[1] "%(count)s обновлений выбрано."
msgstr[2] "%(count)s обновлений выбрано."

#: ../UpdateManager/UpdateManager.py:480
#, python-format
msgid "%s will be downloaded."
msgstr "%s будет загружено."

#: ../UpdateManager/UpdateManager.py:491
msgid "The update has already been downloaded, but not installed"
msgid_plural "The updates have already been downloaded, but not installed"
msgstr[0] "Обновление уже загружено, но ещё не установлено"
msgstr[1] "Обновления уже загружены, но ещё не установлены"
msgstr[2] "Обновления уже загружены, но ещё не установлены"

#: ../UpdateManager/UpdateManager.py:495
msgid "There are no updates to install"
msgstr "Обновления отсутствуют"

#. TRANSLATORS: this allows to switch the order of the count of
#. updates and the download size string (if needed)
#: ../UpdateManager/UpdateManager.py:500
#, python-format
msgid "%(count_str)s %(download_str)s"
msgstr "%(count_str)s %(download_str)s"

#: ../UpdateManager/UpdateManager.py:507
msgid "Unknown download size."
msgstr "Загружаемый размер неизвестен."

#: ../UpdateManager/UpdateManager.py:518
msgid ""
"It is unknown when the package information was updated last. Please try "
"clicking on the 'Check' button to update the information."
msgstr ""
"Время последнего обновления неизвестно. Пожалуйста, нажмите кнопку "
"«Проверить» для получения информации."

#: ../UpdateManager/UpdateManager.py:527
#, python-format
msgid "The package information was last updated %(days_ago)s day ago."
msgid_plural ""
"The package information was last updated %(days_ago)s days ago."
msgstr[0] "Информация о пакетах была обновлена %(days_ago)s день назад."
msgstr[1] "Информация о пакетах была обновлена %(days_ago)s дня назад."
msgstr[2] "Информация о пакетах была обновлена %(days_ago)s дней назад."

#: ../UpdateManager/UpdateManager.py:531
#, python-format
msgid "The package information was last updated %(hours_ago)s hour ago."
msgid_plural ""
"The package information was last updated %(hours_ago)s hours ago."
msgstr[0] "Информация о пакетах была обновлена %(hours_ago)s час назад."
msgstr[1] "Информация о пакетах была обновлена %(hours_ago)s часа назад."
msgstr[2] "Информация о пакетах была обновлена %(hours_ago)s часов назад."

#: ../UpdateManager/UpdateManager.py:535
msgid "The package information was last updated less than one hour ago."
msgstr "Информация о пакетах была обновлена меньше часа назад."

#: ../UpdateManager/UpdateManager.py:555 ../data/glade/UpdateManager.ui.h:23
msgid ""
"Software updates correct errors, eliminate security vulnerabilities and "
"provide new features."
msgstr ""
"Обновления программ исправляют ошибки, уязвимости и добавляют новые "
"возможности."

#: ../UpdateManager/UpdateManager.py:575
msgid "Welcome to Ubuntu"
msgstr "Добро пожаловать в Ubuntu"

#: ../UpdateManager/UpdateManager.py:576
msgid ""
"These software updates have been issued since Ubuntu was released. If you "
"don't want to install them now, choose \"Update Manager\" from the "
"Administration Menu later."
msgstr ""
"Данные обновления программного обеспечения были выпущены после релиза "
"Ubuntu. Если вы не хотите их устанавливать, выберите \"Менеджер обновлений\" "
"из меню Система -> Администрирование позже."

#: ../UpdateManager/UpdateManager.py:579
msgid "Software updates are available for this computer"
msgstr "Доступны обновления программного обеспечения для этого компьютера"

#: ../UpdateManager/UpdateManager.py:580
msgid ""
"If you don't want to install them now, choose \"Update Manager\" from the "
"Administration menu later."
msgstr ""
"Если вы не хотите их устанавливать прямо сейчас, то вы можете сделать это "
"позже через «Менеджер обновлений» из меню Система → Администрирование."

#: ../UpdateManager/UpdateManager.py:629
#, python-format
msgid ""
"The upgrade needs a total of %s free space on disk '%s'. Please free at "
"least an additional %s of disk space on '%s'. Empty your trash and remove "
"temporary packages of former installations using 'sudo apt-get clean'."
msgstr ""
"Для обновления требуется %s свободного места на диске '%s'. Пожалуйста, "
"освободите по крайней мере %s дискового пространства на '%s'. Очистите вашу "
"корзину и удалите временные пакеты установок, выполнив в терминале команду "
"'sudo apt-get clean'."

#: ../UpdateManager/UpdateManager.py:652
msgid ""
"The computer needs to restart to finish installing updates. Please save your "
"work before continuing."
msgstr ""
"Для завершения установки обновлений требуется перезагрузить компьютер. "
"Пожалуйста, сохраните результаты вашей работы перед тем, как продолжить."

#: ../UpdateManager/UpdateManager.py:704
#: ../UpdateManagerHildon/UpdateManagerHildon.py:114
msgid "Reading package information"
msgstr "Чтение информации о пакетах"

#: ../UpdateManager/UpdateManager.py:719
msgid "Connecting..."
msgstr "Подключение..."

#: ../UpdateManager/UpdateManager.py:729
msgid "You may not be able to check for updates or download new updates."
msgstr "Недостаточно прав на проверку или скачивание новых обновлений."

#: ../UpdateManager/UpdateManager.py:846
msgid "Could not initialize the package information"
msgstr "Не удалось получить информацию о пакетах"

#: ../UpdateManager/UpdateManager.py:847
msgid ""
"An unresolvable problem occurred while initializing the package "
"information.\n"
"\n"
"Please report this bug against the 'update-manager' package and include the "
"following error message:\n"
msgstr ""
"При работе с пакетом возникла неразрешимая ошибка.\n"
"\n"
"Пожалуйста, сообщите об этой ошибке пакета 'update-manager' и включите это "
"сообщение:\n"

#: ../UpdateManager/UpdateManager.py:871
msgid ""
"An unresolvable problem occurred while calculating the upgrade.\n"
"\n"
"Please report this bug against the 'update-manager' package and include the "
"following error message:"
msgstr ""
"Критическая ошибка в процессе обработки пакета обновлений.\n"
"\n"
"Пожалуйста, сообщите об этой ошибке пакета 'Менеджер обновлений' и включите "
"это сообщение:"

#: ../UpdateManager/UpdateManager.py:896
msgid " (New install)"
msgstr " (Новая установка)"

#. TRANSLATORS: the b stands for Bytes
#: ../UpdateManager/UpdateManager.py:903
#, python-format
msgid "(Size: %s)"
msgstr "(Размер: %s)"

#: ../UpdateManager/UpdateManager.py:905
#, python-format
msgid "From version %(old_version)s to %(new_version)s"
msgstr "С версии %(old_version)s на %(new_version)s"

#: ../UpdateManager/UpdateManager.py:909
#, python-format
msgid "Version %s"
msgstr "Версия %s"

#: ../UpdateManager/UpdateManager.py:924
msgid "Your Ubuntu release is not supported anymore"
msgstr "Ваша версия Ubuntu больше не поддерживается."

#: ../UpdateManager/UpdateManager.py:925
msgid ""
"You will not get any further security fixes or critical updates. Please "
"Upgrade to a later version of Ubuntu Linux."
msgstr ""
"Вы больше не сможете получать обновления безопасности. Пожалуйста, обновите "
"Ubuntu до более новой версии."

#: ../UpdateManager/UpdateManager.py:932
msgid "Upgrade information"
msgstr "Информация об обновлении"

#: ../UpdateManager/UpdateManager.py:954 ../do-release-upgrade:84
msgid "Release upgrade not possible right now"
msgstr "Обновление релиза сейчас не возможно"

#: ../UpdateManager/UpdateManager.py:955 ../do-release-upgrade:85
#, c-format, python-format
msgid ""
"The release upgrade can not be performed currently, please try again later. "
"The server reported: '%s'"
msgstr ""
"Обновление релиза сейчас не может быть выполнено, попробуйте позже. Сервер "
"сообщил: '%s'"

#: ../UpdateManager/UpdateManager.py:957 ../check-new-release-gtk:85
msgid "Downloading the release upgrade tool"
msgstr "Скачивается программа для обновления дистрибутива"

#: ../UpdateManager/UpdateManager.py:964
#, python-format
msgid "<b>New Ubuntu release '%s' is available</b>"
msgstr "<b>Доступен новый релиз Ubuntu '%s'</b>"

#. we assert a clean cache
#: ../UpdateManager/UpdateManager.py:1003
msgid "Software index is broken"
msgstr "Индекс программ поврежден"

#: ../UpdateManager/UpdateManager.py:1004
msgid ""
"It is impossible to install or remove any software. Please use the package "
"manager \"Synaptic\" or run \"sudo apt-get install -f\" in a terminal to fix "
"this issue at first."
msgstr ""
"Установка или удаление программ невозможна. Для исправления этой ситуации "
"используйте менеджер пакетов Synaptic или запустите в терминале \"sudo apt-"
"get install -f\"."

#: ../UpdateManagerHildon/UpdateManagerHildon.py:136
msgid "Downloading Package Information"
msgstr "Загрузка информации о пакете"

#: ../UpdateManagerHildon/UpdateManagerHildon.py:137
msgid ""
"The repositories are being checked for new, removed, or updated software "
"packages"
msgstr ""
"Репозитории будут проверены на новые, удалённые или обновлённые пакеты "
"программ"

#: ../UpdateManagerHildon/UpdateManagerHildon.py:145
msgid "Downloading Package Updates"
msgstr "Загрузка пакетов обновлений"

#: ../UpdateManagerHildon/UpdateManagerHildon.py:146
msgid ""
"The selected package updates are being downloaded and installed on the system"
msgstr "Выбранные пакеты обновлений скачиваются и устанавливаются в систему"

#: ../UpdateManagerHildon/UpdateManagerHildon.py:152
msgid "run_synaptic called with unknown action"
msgstr "run_synaptic вызвано с неизвестным действием"

#: ../UpdateManagerText/UpdateManagerText.py:26
msgid "Cancel"
msgstr "Отмена"

#: ../UpdateManagerText/UpdateManagerText.py:27
msgid "Install"
msgstr "Установка"

#: ../UpdateManagerText/UpdateManagerText.py:45
msgid "Building Updates List"
msgstr "Формируется список обновлений"

#: ../UpdateManagerText/UpdateManagerText.py:48
msgid ""
"\n"
"A normal upgrade can not be calculated, please run: \n"
"  sudo apt-get dist-upgrade\n"
"\n"
"\n"
"This can be caused by:\n"
" * A previous upgrade which didn't complete\n"
" * Problems with some of the installed software\n"
" * Unofficial software packages not provided by Ubuntu\n"
" * Normal changes of a pre-release version of Ubuntu"
msgstr ""
"\n"
"Обычное обновление не может быть расчитано, пожалуйста, запустите: \n"
"  sudo apt-get dist-upgrade\n"
"\n"
"\n"
"Это может быть вызвано:\n"
" * Предыдущим обновлением, которые не было завершено\n"
" * Проблемами с отдельными установленными пакетами или программами\n"
" * Неофицальными пакетами, которые не поддерживаются Ubuntu\n"
" * Естественными изменениями в предварительной версии Ubuntu"

#: ../UpdateManagerText/UpdateManagerText.py:117
msgid "Downloading changelog"
msgstr "Загрузка списка изменений"

#: ../UpdateManager/Core/MyCache.py:128
#, python-format
msgid "Other updates (%s)"
msgstr "Прочие обновления (%s)"

#: ../UpdateManager/Core/MyCache.py:285
#, python-format
msgid ""
"Changes for the versions:\n"
"%s\n"
"%s\n"
"\n"
msgstr ""
"Изменения в версиях:\n"
"%s\n"
"%s\n"
"\n"

#: ../UpdateManager/Core/MyCache.py:298
msgid "This change is not coming from a source that supports changelogs."
msgstr ""
"Это изменение внесено не из источника с поддержкой истории изменений."

#: ../UpdateManager/Core/MyCache.py:304 ../UpdateManager/Core/MyCache.py:324
msgid ""
"Failed to download the list of changes. \n"
"Please check your Internet connection."
msgstr ""
"Ошибка при загрузке списка изменений. \n"
"Проверьте ваше сетевое соединение."

#: ../UpdateManager/Core/MyCache.py:313
#, python-format
msgid ""
"The changelog does not contain any relevant changes.\n"
"\n"
"Please use http://launchpad.net/ubuntu/+source/%s/%s/+changelog\n"
"until the changes become available or try again later."
msgstr ""
"Список изменений не содержит связанных с пакетом записей.\n"
"\n"
"Пожалуйста, используйте "
"http://launchpad.net/ubuntu/+source/%s/%s/+changelog\n"
"пока не станет доступен список изменений или попробуйте позже."

#: ../UpdateManager/Core/MyCache.py:318
#, python-format
msgid ""
"The list of changes is not available yet.\n"
"\n"
"Please use http://launchpad.net/ubuntu/+source/%s/%s/+changelog\n"
"until the changes become available or try again later."
msgstr ""
"Список изменений пока не доступен.\n"
"\n"
"Пожалуйста, посмотрите http://launchpad.net/ubuntu/+source/%s/%s/+changelog\n"
"пока изменения не станут доступны или попробуйте еще раз позднее."

#: ../UpdateManager/Core/UpdateList.py:52
msgid "Failed to detect distribution"
msgstr "Не удалось определить дистрибутив"

#: ../UpdateManager/Core/UpdateList.py:53
#, python-format
msgid "A error '%s' occurred while checking what system you are using."
msgstr ""
"Произошла ошибка '%s' во время проверки какую систему вы используете."

#: ../UpdateManager/Core/UpdateList.py:64
msgid "Important security updates"
msgstr "Важные обновления безопасности"

#: ../UpdateManager/Core/UpdateList.py:65
msgid "Recommended updates"
msgstr "Рекомендованные обновления"

#: ../UpdateManager/Core/UpdateList.py:66
msgid "Proposed updates"
msgstr "Предлагаемые обновления"

#: ../UpdateManager/Core/UpdateList.py:67
msgid "Backports"
msgstr "Адаптации из более поздних версий (backports)"

#: ../UpdateManager/Core/UpdateList.py:68
msgid "Distribution updates"
msgstr "Обновления дистрибутива"

#: ../UpdateManager/Core/UpdateList.py:73
msgid "Other updates"
msgstr "Прочие обновления"

#: ../UpdateManager/Core/UpdateList.py:82
msgid "Previous selected"
msgstr "Прежде выбранные"

#: ../data/glade/UpdateManager.ui.h:1
msgid ""
"<b><big>You must check for updates manually</big></b>\n"
"\n"
"Your system does not check for updates automatically. You can configure this "
"behavior in <i>Software Sources</i> on the <i>Updates</i> tab."
msgstr ""
"<b><big>Вы должны проверить наличие обновлений вручную</big></b>\n"
"\n"
"Ваша система не проверяет наличие обновлений автоматически. Вы можете "
"настроить это в <i>Источники приложений</i> на вкладке <i>Обновления</i>."

#: ../data/glade/UpdateManager.ui.h:4
msgid "<big><b>Not all updates can be installed</b></big>"
msgstr "<big><b>Не все обновления возможно установить</b></big>"

#: ../data/glade/UpdateManager.ui.h:5
msgid "<big><b>Running on battery</b></big>"
msgstr "<big><b>Работа от батареи</b></big>"

#: ../data/glade/UpdateManager.ui.h:6
msgid "<big><b>Starting Update Manager</b></big>"
msgstr "<big><b>Запускается Менеджер обновлений</b></big>"

#: ../data/glade/UpdateManager.ui.h:7
msgid "Changes"
msgstr "Изменения"

#: ../data/glade/UpdateManager.ui.h:8
msgid "Chec_k"
msgstr "_Проверить"

#: ../data/glade/UpdateManager.ui.h:9
msgid "Co_ntinue"
msgstr "_Продолжить"

#: ../data/glade/UpdateManager.ui.h:10
msgid "Description"
msgstr "Описание"

#: ../data/glade/UpdateManager.ui.h:11
msgid "Description of update"
msgstr "Описание обновления"

#: ../data/glade/UpdateManager.ui.h:12
msgid ""
"It&#x2019;s safer to connect the computer to AC power before updating."
msgstr ""
"Перед обновлением безопаснее будет подключить компьютер к источнику питания."

#: ../data/glade/UpdateManager.ui.h:14
msgid ""
"Run a partial upgrade, to install as many updates as possible. \n"
"\n"
"This can be caused by:\n"
" * A previous upgrade which didn't complete\n"
" * Problems with some of the installed software\n"
" * Unofficial software packages not provided by Ubuntu\n"
" * Normal changes of a pre-release version of Ubuntu"
msgstr ""
"Запустить частичное обновление дистрибутива с установкой по возможности "
"максимального количества обновлений.\n"
"Возможные причины:\n"
"\n"
"* Предыдущая попытка обновления дистрибутива не завершилась\n"
"* Проблема с каким-либо установленным ПО\n"
"* Неофициальные пакеты, непредоставляемые Ubuntu\n"
"* Нормальные изменения предрелизной версии Ubuntu"

#: ../data/glade/UpdateManager.ui.h:21
msgid "Settings..."
msgstr "Настройки..."

#: ../data/glade/UpdateManager.ui.h:22
#: ../data/glade/UpgradePromptDialog.ui.h:5
msgid "Show progress of individual files"
msgstr "Показывать прогресс для отдельных файлов"

#: ../data/glade/UpdateManager.ui.h:24
msgid "Starting Update Manager"
msgstr "Запуск менеджера обновлений"

#: ../data/glade/UpdateManager.ui.h:25
msgid "U_pgrade"
msgstr "_Обновить"

#: ../data/glade/UpdateManager.ui.h:26 ../data/update-manager.desktop.in.h:3
#: ../data/update-manager-hildon.desktop.in.h:3
msgid "Update Manager"
msgstr "Менеджер обновлений"

#: ../data/glade/UpdateManager.ui.h:27
msgid "Your system is running on battery. Are you sure you want to continue?"
msgstr ""
"Ваш компьютер работает от батареи. Вы уверены, что хотите продолжить?"

#: ../data/glade/UpdateManager.ui.h:28
msgid "_Hide this information in the future"
msgstr "_Не показывать эту информацию в дальнейшем"

#: ../data/glade/UpdateManager.ui.h:29
msgid "_Install Updates"
msgstr "_Установить обновления"

#: ../data/glade/UpdateManager.ui.h:30
msgid "_Partial Upgrade"
msgstr "_Частичное обновление"

#: ../data/glade/UpdateManager.ui.h:32
msgid "_Upgrade"
msgstr "_Обновить"

#: ../data/glade/UpdateManager.ui.h:33
msgid "updates"
msgstr "обновления"

#: ../data/glade/UpgradePromptDialog.ui.h:1
msgid ""
"<b>A new version of Ubuntu is available. Would you like to upgrade?</b>"
msgstr "<b>Доступна новая версия Ubuntu. Хотите обновить?</b>"

#: ../data/glade/UpgradePromptDialog.ui.h:2
msgid "Ask Me Later"
msgstr "Спросить позже"

#: ../data/glade/UpgradePromptDialog.ui.h:3
msgid "Don't Upgrade"
msgstr "Не обновлять"

#: ../data/glade/UpgradePromptDialog.ui.h:6
msgid "Yes, Upgrade Now"
msgstr "Да, обновить сейчас"

#: ../data/glade/UpgradePromptDialog.ui.h:7
msgid ""
"You can upgrade at a later time by opening Update Manager and click on "
"\"Upgrade\"."
msgstr ""
"Вы можете обновить систему позже, открыв Менеджер Обновлений и нажав "
"«Установить обновления»"

#: ../data/glade/UpgradePromptDialog.ui.h:8
msgid "You have declined to upgrade to the new Ubuntu"
msgstr "Вы отклонили обновление до новой версии Ubuntu"

#: ../data/update-manager.desktop.in.h:1
#: ../data/update-manager-hildon.desktop.in.h:1
msgid "Show and install available updates"
msgstr "Показать и установить доступные обновления"

#: ../data/update-manager.desktop.in.h:2
#: ../data/update-manager-hildon.desktop.in.h:2
msgid "Software Updates"
msgstr "Обновления программ"

#: ../data/update-manager.schemas.in.h:1
msgid "*deprecated* Check for new distribution releases"
msgstr "*исключено* Проверка наличия новых выпусков дистрибутива"

#: ../data/update-manager.schemas.in.h:2
msgid "Auto close the install window after successful install"
msgstr "Автоматически закрыть окно установщика после успешной установки"

#: ../data/update-manager.schemas.in.h:3
msgid "First run welcome message"
msgstr "Приветственное сообщение при первом запуске"

#: ../data/update-manager.schemas.in.h:4
msgid ""
"If automatic checking for updates is disabled, you have to reload the "
"channel list manually. This option allows to hide the reminder shown in this "
"case."
msgstr ""
"Если автоматическая проверка обновлений отключена, вам придётся обновлять "
"список источников вручную. Этот параметр позволяет скрыть показываемое в "
"данном случае напоминание."

#: ../data/update-manager.schemas.in.h:5
msgid "If this key is set a first run welcome message will be presented."
msgstr "Если параметр отмечен, приветственное сообщение будет показано."

#: ../data/update-manager.schemas.in.h:6
msgid ""
"If this key is set the install window will be automatically closed on "
"successful installation."
msgstr ""
"Если флажок установлен, окно установки будет автоматически закрыто после "
"завершения установки."

#: ../data/update-manager.schemas.in.h:7
msgid ""
"If this key is set the main update list window will show version information "
"(from version to version)."
msgstr ""
"Если этот ключ установлен, в главном окне списка обновлений будет "
"отображаться информация о версиях (от версии к версии)"

#: ../data/update-manager.schemas.in.h:8
msgid ""
"If this key is set, the main update list window will show the package "
"summary before the package name."
msgstr ""
"Если этот ключ установлен, окно главного списка обновлений будет показывать "
"информацию о пакете перед его именем."

#: ../data/update-manager.schemas.in.h:9
msgid "Remind to reload the channel list"
msgstr "Напоминать об обновлении списка источников"

#: ../data/update-manager.schemas.in.h:10
msgid "Show details of an update"
msgstr "Показать подробности обновления"

#: ../data/update-manager.schemas.in.h:11
msgid "Show package summary before package name in update list"
msgstr "Показать информацию о пакете перед именем пакета в списке обновления"

#: ../data/update-manager.schemas.in.h:12
msgid "Show version in update list"
msgstr "Показывать версию в списке обновлений"

#: ../data/update-manager.schemas.in.h:13
msgid "Stores the size of the update-manager dialog"
msgstr "Хранит размер окна менеджера обновлений"

#: ../data/update-manager.schemas.in.h:14
msgid ""
"Stores the state of the expander that contains the list of changes and the "
"description"
msgstr "Хранит состояние панели, содержащей описание и список изменений"

#: ../data/update-manager.schemas.in.h:15
msgid "The window size"
msgstr "Размер окна"

#: ../data/update-manager.schemas.in.h:16
msgid ""
"This key is deprecated in favor of the file /etc/update-manager/release-"
"upgrades Check automatically if a new version of the current distribution is "
"available and offer to upgrade (if possible)."
msgstr ""
"Этот ключ был исключён по причине того, что /etc/update-manager/release-"
"upgrades производит автоматическую проверку на наличие новых версий и "
"предлагает обновление (если доступно)."

#: ../data/update-manager.schemas.in.h:17
msgid ""
"This will permanently hide the new release prompt from check-new-release-"
"gtk. Note that the small button in the main update-manager UI will still be "
"there."
msgstr ""
"Подсказка о новых выпусках не будет отображена при обращении к модулю check-"
"new-release-gtk. Обратите внимание, что небольшая кнопка в главном окне "
"Менеджера обновлений будет по-прежнему видна."

#: ../data/update-manager.schemas.in.h:18
msgid "make check-new-release-gtk ignore a given new release"
msgstr ""
"Игнорировать новые версии дистрибутива при обращении к check-new-release-gtk"

#: ../update-manager:53 ../do-release-upgrade:33
msgid "Show version and exit"
msgstr "Показать версию и выйти"

#: ../update-manager:56
msgid "Directory that contains the data files"
msgstr "Каталог, который содержит файлы данных"

#: ../update-manager:59
msgid "Check if a new Ubuntu release is available"
msgstr "Проверить, доступен ли новый выпуск дистрибутива Ubuntu"

#: ../update-manager:62 ../do-release-upgrade:36 ../check-new-release-gtk:136
msgid "Check if upgrading to the latest devel release is possible"
msgstr ""
"Проверка возможности обновления до последней нестабильной версии дистрибутива"

#: ../update-manager:66
msgid "Upgrade using the latest proposed version of the release upgrader"
msgstr "Обновление с использованием последней версии менеджера обновлений"

#: ../update-manager:73
msgid "Do not focus on map when starting"
msgstr "Не выбирать карту при запуске"

#: ../update-manager:76
msgid "Try to run a dist-upgrade"
msgstr "Попробовать запустить dist-upgrade"

#: ../update-manager:80 ../do-release-upgrade:52
msgid "Test upgrade with a sandbox aufs overlay"
msgstr "Протестировать обновление в безопасном режиме"

#: ../update-manager:100
msgid "Running partial upgrade"
msgstr "Идёт частичное обновление"

#: ../do-release-upgrade:40 ../check-new-release-gtk:140
msgid ""
"Try upgrading to the latest release using the upgrader from $distro-proposed"
msgstr ""
"Попробуйте обновиться до самого последнего выпуска с помощью $distro-proposed"

#: ../do-release-upgrade:44
msgid ""
"Run in a special upgrade mode.\n"
"Currently 'desktop' for regular upgrades of a desktop system and 'server' "
"for server systems are supported."
msgstr ""
"Запустить в специальном режиме обновления.\n"
"В настоящее время поддерживается регулярное обновление для 'настольных' и "
"'серверных' систем."

#: ../do-release-upgrade:50
msgid "Run the specified frontend"
msgstr "Запустить указанный интерфейс"

#: ../do-release-upgrade:55
msgid ""
"Check only if a new distribution release is available and report the result "
"via the exit code"
msgstr ""
"Проверять наличие новой версии дистрибутива и возвращать результат с помощью "
"кода выхода"

#: ../do-release-upgrade:69
msgid "Checking for a new ubuntu release"
msgstr "Проверка наличия новой версии Ubuntu"

#: ../do-release-upgrade:79
msgid "No new release found"
msgstr "Новая версия не обнаружена"

#: ../do-release-upgrade:91
#, c-format
msgid "New release '%s' available."
msgstr "Доступен новый релиз '%s'."

#: ../do-release-upgrade:92
msgid "Run 'do-release-upgrade' to upgrade to it."
msgstr "Чтобы обновиться до него, выполните 'do-release-upgrade'."

#: ../check-new-release-gtk:65
msgid "Ubuntu %(version)s Upgrade Available"
msgstr "Доступно обновление Ubuntu %(version)s"

#: ../check-new-release-gtk:101
#, c-format
msgid "You have declined the upgrade to Ubuntu %s"
msgstr "Вы отклонили обновление до Ubuntu %s"

#: ../Janitor/computerjanitor/exc.py:30
#, python-format
msgid "Unimplemented method: %s"
msgstr "Невыполненный метод: %s"

#: ../Janitor/computerjanitor/file_cruft.py:46
msgid "A file on disk"
msgstr "Файл на диске"

#: ../Janitor/computerjanitor/package_cruft.py:45
msgid ".deb package"
msgstr ".deb пакет"

#: ../Janitor/computerjanitor/missing_package_cruft.py:33
msgid "Install missing package."
msgstr "Установить отсутствующий пакет."

#: ../Janitor/computerjanitor/missing_package_cruft.py:42
#, python-format
msgid "Package %s should be installed."
msgstr "Необходимо установить пакет %s."

#. pragma: no cover
#: ../Janitor/plugins/dpkg_status_plugin.py:36
#, python-format
msgid "%i obsolete entries in the status file"
msgstr "Устарелое содержимое %i в файле статуса"

#: ../Janitor/plugins/dpkg_status_plugin.py:39
msgid "Obsolete entries in dpkg status"
msgstr "Устарелое содержимое в статусе dpkg"

#. pragma: no cover
#: ../Janitor/plugins/dpkg_status_plugin.py:42
msgid "Obsolete dpkg status entries"
msgstr "Устарелое содержимое статусов dpkg"

#: ../Janitor/plugins/kdelibs4to5_plugin.py:39
msgid ""
"When upgrading, if kdelibs4-dev is installed, kdelibs5-dev needs to be "
"installed. See bugs.launchpad.net, bug #279621 for details."
msgstr ""
"При обновлении, необходимо установить kdelibs5-dev, если установлен kdelibs4-"
"dev. Это баг о котором можно прочитать здесь - bugs.launchpad.net, bug "
"#279621"

#: ../Janitor/plugins/langpack_manual_plugin.py:34
#, python-format
msgid "%s needs to be marked as manually installed."
msgstr "%s должен быть помечен как установленный вручную."

#: ../Janitor/plugins/remove_lilo_plugin.py:28
msgid ""
"Remove lilo since grub is also installed.(See bug #314004 for details.)"
msgstr "Удалите lilo, если grub уже установлен. (bug #314004 для деталей)"

#, python-format
#~ msgid "The package information was last updated %s hour ago."
#~ msgid_plural "The package information was last updated %s hours ago."
#~ msgstr[0] "Информация о пакетах в системе была обновлена %s час назад."
#~ msgstr[1] "Информация о пакетах в системе была обновлена %s часа назад."
#~ msgstr[2] "Информация о пакетах в системе была обновлена %s часов назад."

#, python-format
#~ msgid "The package information was last updated %s day ago."
#~ msgid_plural "The package information was last updated %s days ago."
#~ msgstr[0] "Информация о пакетах в системе была обновлена %s день назад."
#~ msgstr[1] "Информация о пакетах в системе была обновлена %s дня назад."
#~ msgstr[2] "Информация о пакетах в системе была обновлена %s дней назад."

#~ msgid "Unknown download size"
#~ msgstr "Неизвестный размер загружаемых данных"

#, python-format
#~ msgid "<b>Downgrade %s</b>"
#~ msgstr "<b>Заменить старыми %s</b>"

#~ msgid "Support for some applications ended"
#~ msgstr "Некоторые программы больше не поддерживаются"

#~ msgid ""
#~ "The upgrade is now aborted. Your system could be in an unusable state. A "
#~ "recovery will run now (dpkg --configure -a)."
#~ msgstr ""
#~ "Обновление прервано. Ваша система возможно находится в нестабильном "
#~ "состоянии. Для восстановления выполните (dpkg --configure -a)."

#~ msgid ""
#~ "The upgrade is now aborted. Please check your Internet connection or "
#~ "installation media and try again. All files downloaded so far are kept."
#~ msgstr ""
#~ "Обновление прервано. Пожалуйста, проверьте ваше соединение с интернетом или  "
#~ "источники приложений и повторите попытку. Все ранее загруженные файлы будут "
#~ "сохранены."

#, python-format
#~ msgid ""
#~ "The upgrade is now aborted. The upgrade needs a total of %s free space on "
#~ "disk '%s'. Please free at least an additional %s of disk space on '%s'. "
#~ "Empty your trash and remove temporary packages of former installations using "
#~ "'sudo apt-get clean'."
#~ msgstr ""
#~ "Обновление прервано. Для обновления необходимо %s свободного пространства на "
#~ "диске '%s'. Пожалуйста, освободите как минимум %s дискового пространства на "
#~ "'%s'. Очистите корзину и удалите загруженные фалы пакетов используя команду "
#~ "'sudo apt-get clean'."

#~ msgid ""
#~ "The upgrade is now aborted. Please check your Internet connection or "
#~ "installation media and try again. "
#~ msgstr ""
#~ "Обновление прервано. Пожалуйста, проверьте ваше соединение с интернетом или  "
#~ "источники приложений и повторите попытку. "

#~ msgid ""
#~ "Please report this as a bug and include the files /var/log/dist-"
#~ "upgrade/main.log and /var/log/dist-upgrade/apt.log in your report. The "
#~ "upgrade is now aborted.\n"
#~ "Your original sources.list was saved in /etc/apt/sources.list.distUpgrade."
#~ msgstr ""
#~ "Сообщите об этой ошибке и приложите к отчёту файлы /var/log/dist-"
#~ "upgrade/main.log и /var/log/dist-upgrade/apt.log. Обновление системы "
#~ "прервано.\n"
#~ "Ваш файл sources.list был сохранён в /etc/apt/sources.list.distUpgrade."

#~ msgid ""
#~ "Please report this as a bug (if you haven't already) and include the files "
#~ "/var/log/dist-upgrade/main.log and /var/log/dist-upgrade/apt.log in your "
#~ "report. The upgrade is now aborted.\n"
#~ "Your original sources.list was saved in /etc/apt/sources.list.distUpgrade."
#~ msgstr ""
#~ "Пожалуйста, сообщите об это ошибке и приложите к отчёту файлы /var/log/dist-"
#~ "upgrade/main.log и /var/log/dist-upgrade/apt.log. Обновление будет "
#~ "прервано.\n"
#~ "Ваш файл sources.list был сохранён в /etc/apt/sources.list.distUpgrade."

#~ msgid "Restart _Later"
#~ msgstr "Перезагрузить _позже"

#~ msgid "<b><big>Upgrading Ubuntu to version 10.04 LTS</big></b>"
#~ msgstr "<b><big>Обновление Ubuntu до версии 10.04 LTS</big></b>"

#, python-format
#~ msgid ""
#~ "Download size: %s\n"
#~ "%s selected."
#~ msgstr ""
#~ "Размер закачки: %s\n"
#~ "%s выбрано."

#~ msgid ""
#~ "Canonical Ltd. no longer provides support for the following software "
#~ "packages. You can still get support from the community."
#~ msgstr ""
#~ "Canonical Ltd. больше не обеспечивает поддержки следующих пакетов программ. "
#~ "Однако вы можете получить поддержку у сообщества."

#~ msgid ""
#~ "Canonical Ltd. no longer provides support for the following software "
#~ "packages. You can still get support from the community.\n"
#~ "\n"
#~ "These packages will be suggested for removal at the end of the upgrade "
#~ "because you have not enabled the community maintained software channel "
#~ "(universe)."
#~ msgstr ""
#~ "Canonical Ltd. больше не обеспечивает поддержки следующих пакетов программ. "
#~ "Однако вы можете получить поддержку у сообщества.\n"
#~ "\n"
#~ "Эти пакеты будут предложены для удаления по окончанию процесса обновления "
#~ "дистрибутива, так как вы не включили репозиторий сообщества (universe)."
